In [2]:
# conda activate dream

library(sva)
library(edgeR)
library(limma)
library(dplyr)
library(data.table)

setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex")

In [3]:
batch_ANOVA <- function(pca, sampleinfo, batch_cols) {
    for (i in batch_cols) {
        batch_label <- colnames(sampleinfo)[i]
        batch <- factor(sampleinfo[,i])
        if (length(levels(batch)) > 1) {
            if (batch_label == "Mean_age") {
                batch <- sampleinfo[,i] 
            }
            fit <- lm(pca$x[,2] ~ batch)
            pc_test <- anova(fit)$`Pr(>F)`[1]
            print(paste(batch_label, p.adjust(pc_test, "BH")))
        }
    }
}

In [4]:
sampleinfo <- fread("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/bulk/GTEx/cortex/GTEx_cortex_sampleinfo.csv", data.table=FALSE)

In [14]:
sampleinfo$Mean_age <- sapply(strsplit(sampleinfo$AGE, "-"), function(x) mean(as.numeric(x)))

batch_cols <- c(
    grep("Mean_age", colnames(sampleinfo)),
    grep("SMCENTER", colnames(sampleinfo)),
    grep("SMNABTCH$", colnames(sampleinfo)), 
    grep("SMGEBTCH$", colnames(sampleinfo)),
    grep("SEX", colnames(sampleinfo)),
    grep("SMTSD", colnames(sampleinfo)),
    grep("DTHHRDY", colnames(sampleinfo))
)

## Starting from TPM SN QN rd2 data

### Prep data

In [ ]:
sampleinfo <- fread("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/bulk/GTEx/cortex/GTEx_cortex_sampleinfo.csv", data.table=FALSE)
expr <- fread("GTEx_cortex_TPM_rd2_SampleNetworks/All_02-16-53/GTEx_cortex_TPM_rd2_All_501_outliers_removed.csv", data.table=FALSE)

In [8]:
expr[1:4,1:4]

  datExprT...c.1.skip1.. GTEX.111FC.0011.R3b.SM.GJ3PN
1 DDX11L1                0.0000000
2 WASH7P                 2.5457173
3 MIR6859-1              0.0000000
4 MIR1302-2HG            0.0477403
  GTEX.117XS.0011.R3a.SM.GIN8W GTEX.1192X.0011.R3b.SM.GIN8Y
1 0.000000                     0.000000
2 3.642921                     2.463347
3 0.000000                     0.000000
4 0.000000                     0.000000

In [9]:
sampleinfo[,1] <- make.names(sampleinfo[,1])
sampleinfo <- sampleinfo[match(colnames(expr)[-1], sampleinfo[,1]),]
sampleinfo$Mean_age <- sapply(strsplit(sampleinfo$AGE, "-"), function(x) mean(as.numeric(x)))

In [10]:
# For duplicate genes, choose row with highest mean expression

mean_expr <- data.frame(
    Index=1:nrow(expr), 
    Gene=expr[,1], 
    Expr=rowMeans(expr[,-1])
)

mean_expr <- mean_expr %>%
    group_by(Gene) %>%
    slice_max(Expr)

print(dim(mean_expr))

expr <- expr[mean_expr$Index,]

# Subset to genes in the top X percentile of mean expression

prob <- .6
mean_expr <- rowMeans(expr[,-1])
print(sum(mean_expr >= quantile(mean_expr, prob)))
expr_filtered <- expr[mean_expr >= quantile(mean_expr, prob),]

[1] 55692     3
[1] 22277

In [11]:
rownames(expr_filtered) <- expr_filtered[,1]
dat <- expr_filtered[,-1]
dim(dat)

[1] 22277   501

### Check significance of batch variables

In [12]:
# Before ComBat

pca <- prcomp(t(dat), center=TRUE, scale.=TRUE)

In [15]:
batch_ANOVA(pca, sampleinfo, batch_cols)

[1] "Mean_age 0.015510282443709"
[1] "SMCENTER 8.91598908338723e-87"
[1] "SMNABTCH 8.52924667374512e-26"
[1] "SMGEBTCH 1.22443325388007e-11"
[1] "SEX 0.153850676386419"
[1] "SMTSD 2.61126263815865e-90"
[1] "DTHHRDY 0.214553918008083"

### Run ComBat

In [17]:
mod <- model.matrix(~Mean_age + as.factor(SEX) + as.factor(SMTSD), data=sampleinfo)

batch <- factor(sampleinfo$SMGEBTCH)

expr_combat1 <- sva::ComBat(
    dat,
    batch,
    mod=mod,
    mean.only=FALSE,
    par.prior=TRUE,
    prior.plots=FALSE
)

Found 1317 genes with uniform expression within a single batch (all zeros); these will not be adjusted for batch.

Using the 'mean only' version of ComBat

Found173batches

Note: one batch has only one sample, setting mean.only=TRUE

Adjusting for4covariate(s) or covariate level(s)

Standardizing Data across genes

Fitting L/S model and finding priors

Finding parametric adjustments

Adjusting the Data

### Check significance of batch variables

In [18]:
# After ComBat

pca <- prcomp(t(expr_combat1), center=TRUE, scale.=TRUE)

batch_ANOVA(pca, sampleinfo, batch_cols)

[1] "Mean_age 0.0938632610218132"
[1] "SMCENTER 1.96363192409567e-129"
[1] "SMNABTCH 1.25040920917601e-32"
[1] "SMGEBTCH 3.03841356887261e-06"
[1] "SEX 0.095489325034402"
[1] "SMTSD 3.68645233998238e-137"
[1] "DTHHRDY 0.348631538035072"

### Run ComBat again

In [19]:
mod <- model.matrix(~Mean_age + as.factor(SEX) + as.factor(sampleinfo$SMTSD), data=sampleinfo)

batch <- as.factor(sampleinfo$SMGEBTCH)

expr_combat2 <- sva::ComBat(
    expr_combat1,
    batch=batch,
    mod=mod,
    mean.only=FALSE,
    par.prior=TRUE,
    prior.plots=FALSE
)

Found 1317 genes with uniform expression within a single batch (all zeros); these will not be adjusted for batch.

Using the 'mean only' version of ComBat

Found173batches

Note: one batch has only one sample, setting mean.only=TRUE

Adjusting for4covariate(s) or covariate level(s)

Standardizing Data across genes

Fitting L/S model and finding priors

Finding parametric adjustments

Adjusting the Data

### Check significance of batch variables

In [20]:
pca <- prcomp(t(expr_combat2), center=TRUE, scale.=TRUE)

batch_ANOVA(pca, sampleinfo, batch_cols)

[1] "Mean_age 0.13004596907701"
[1] "SMCENTER 1.71452051851891e-136"
[1] "SMNABTCH 1.02562465410297e-33"
[1] "SMGEBTCH 1.24831697268674e-05"
[1] "SEX 0.0903052859833676"
[1] "SMTSD 1.17942841538618e-145"
[1] "DTHHRDY 0.416928297792487"

In [ ]:
# Didn't improve batch significance that much. Saving less processed version.

In [21]:
fwrite(expr_combat1, file=paste0("data/GTEx_cortex_TPM_rd2_All_501_outliers_removed_ComBat_SMGEBTCH_corrected.csv"), row.names=TRUE)

x being coerced from class: matrix to data.table

## Starting from counts SN rd2 data

### Prep data

In [22]:
sampleinfo <- fread("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/bulk/GTEx/cortex/GTEx_cortex_sampleinfo.csv", data.table=FALSE)
expr <- fread("GTEx_cortex_counts_rd2_SampleNetworks/All_02-39-09/GTEx_cortex_counts_rd2_All_501_outliers_removed.csv", data.table=FALSE)

In [25]:
expr[1:5,1:4]

  datExprT...c.1.skip1.. GTEX.111FC.0011.R3b.SM.GJ3PN
1 DDX11L1                  0
2 WASH7P                 144
3 MIR6859-1                0
4 MIR1302-2HG              2
5 FAM138A                  0
  GTEX.117XS.0011.R3a.SM.GIN8W GTEX.1192X.0011.R3b.SM.GIN8Y
1   0                            0
2 164                          134
3   0                            0
4   0                            0
5   0                            0

In [26]:
sampleinfo[,1] <- make.names(sampleinfo[,1])
sampleinfo <- sampleinfo[match(colnames(expr)[-1], sampleinfo[,1]),]
sampleinfo$Mean_age <- sapply(strsplit(sampleinfo$AGE, "-"), function(x) mean(as.numeric(x)))

In [27]:
# For duplicate genes, choose row with highest mean expression

mean_expr <- data.frame(
    Index=1:nrow(expr), 
    Gene=expr[,1], 
    Expr=rowMeans(expr[,-1])
)

mean_expr <- mean_expr %>%
    group_by(Gene) %>%
    slice_max(Expr)

print(dim(mean_expr))

expr <- expr[mean_expr$Index,]

# Subset to genes in the top X percentile of mean expression

prob <- .6
mean_expr <- rowMeans(expr[,-1])
print(sum(mean_expr >= quantile(mean_expr, prob)))
expr_filtered <- expr[mean_expr >= quantile(mean_expr, prob),]

[1] 55442     3
[1] 22178

In [28]:
dim(expr_filtered)

[1] 22178   502

In [29]:
total_expr <- colSums(expr_filtered[,-1])
expr_norm <- sweep(expr_filtered[,-1], MARGIN=2, FUN="/", STATS=total_expr) * 1e4

In [30]:
rownames(expr_norm) <- expr_filtered[,1]
dat <- expr_norm
dim(dat)

[1] 22178   501

### Check significance of batch variables

In [31]:
# Before ComBat

pca <- prcomp(t(dat), center=TRUE, scale.=TRUE)

In [ ]:
batch_ANOVA(pca, sampleinfo, batch_cols)

[1] "Mean_age 0.00344516235382899"
[1] "SMCENTER 1.66702982593877e-24"
[1] "SMNABTCH 1.9630378682996e-07"
[1] "SMGEBTCH 0.00408343915285182"
[1] "SEX 0.000361061746848544"
[1] "SMTSD 2.50638132475145e-26"
[1] "DTHHRDY 2.46286897851178e-10"

### Run ComBat

In [32]:
mod <- model.matrix(~Mean_age + as.factor(SEX) + as.factor(SMTSD), data=sampleinfo)

batch <- factor(sampleinfo$SMGEBTCH)

expr_combat1 <- sva::ComBat(
    dat,
    batch,
    mod=mod,
    mean.only=FALSE,
    par.prior=TRUE,
    prior.plots=FALSE
)

Found 268 genes with uniform expression within a single batch (all zeros); these will not be adjusted for batch.

Using the 'mean only' version of ComBat

Found177batches

Note: one batch has only one sample, setting mean.only=TRUE

Adjusting for4covariate(s) or covariate level(s)

Standardizing Data across genes

Fitting L/S model and finding priors

Finding parametric adjustments

Adjusting the Data

### Check significance of batch variables

In [33]:
# After ComBat

pca <- prcomp(t(expr_combat1), center=TRUE, scale.=TRUE)

batch_ANOVA(pca, sampleinfo, batch_cols)

[1] "Mean_age 1.43463633975612e-05"
[1] "SMCENTER 8.21544122792259e-72"
[1] "SMNABTCH 1.23780179343228e-14"
[1] "SMGEBTCH 0.418394612274922"
[1] "SEX 0.0146091363796296"
[1] "SMTSD 1.33189406493509e-74"
[1] "DTHHRDY 4.20625993290282e-07"

In [34]:
fwrite(expr_combat1, file=paste0("data/GTEx_cortex_counts_rd2_All_501_outliers_removed_ComBat_SMGEBTCH_corrected.csv"), row.names=TRUE)

x being coerced from class: matrix to data.table

In [35]:
expr_combat1

            GTEX.111FC.0011.R3b.SM.GJ3PN GTEX.117XS.0011.R3a.SM.GIN8W
A1BG        0.046613223                  4.188489e-02
A1BG-AS1    0.038178968                  1.148113e-02
A2M         0.874489282                  1.424826e+00
A2M-AS1     0.012091020                  2.442174e-02
A2ML1       0.025997187                  3.587366e-02
A2MP1       0.001333547                  2.160876e-03
A4GALT      0.021452925                  3.492755e-02
AAAS        0.253598871                  2.366756e-01
AACS        0.951621989                  4.168160e-01
AACSP1      0.006242163                  3.619118e-03
AADAT       0.131735630                  1.160182e-01
AAGAB       0.542402312                  2.556627e-01
AAK1        1.937561884                  1.036145e+00
AAMDC       0.015743357                  1.851769e-02
AAMP        0.966329268                  6.080193e-01
AANAT       0.007549184                  5.001171e-03
AAR2        0.161840563                  1.275327e-01
AARD        0.008662728                  9.375955e-03
AARS1       2.557063131                  1.239511e+00
AARS2       0.282298295                  2.305214e-01
AARSD1      0.311372443                  2.368710e-01
AARSD1P1    0.001807786                  7.488203e-05
AASDH       0.075157291                  7.586403e-02
AASDHPPT    0.826802467                  6.809153e-01
AASS        0.143902695                  1.938017e-01
AATBC       0.009746265                  1.693485e-03
AATF        0.187041364                  1.425101e-01
AATK        1.521895193                  1.347887e+00
ABAT        3.935645251                  3.708385e+00
ABCA1       0.057240883                  6.375292e-02
⋮           ⋮                            ⋮
ZSCAN23     0.005647697                  0.004577917
ZSCAN25     0.087092951                  0.053241551
ZSCAN26     0.181047228                  0.150047113
ZSCAN29     0.146113533                  0.127498448
ZSCAN30     0.224366805                  0.150230626
ZSCAN31     0.100397811                  0.049088161
ZSCAN32     0.080174614                  0.095606485
ZSCAN5A     0.038694414                  0.033059270
ZSCAN5A-AS1 0.003306243                  0.002031319
ZSCAN9      0.051896587                  0.043770991
ZSWIM1      0.095956708                  0.062767838
ZSWIM3      0.058183649                  0.021404589
ZSWIM4      0.024635378                  0.016101789
ZSWIM5      0.125093899                  0.079168814
ZSWIM6      0.209723804                  0.175497190
ZSWIM7      0.161935084                  0.219004152
ZSWIM8      0.627184492                  0.386133695
ZSWIM8-AS1  0.004636735                  0.002922487
ZSWIM9      0.285702402                  0.245262464
ZUP1        0.079463592                  0.044555452
ZW10        0.091333422                  0.057159800
ZWILCH      0.072931688                  0.066506977
ZWINT       0.040629964                  0.020713645
ZXDA        0.032842561                  0.028535355
ZXDB        0.134839279                  0.094542614
ZXDC        0.113944655                  0.086859753
ZYG11B      0.838414277                  0.586905846
ZYX         0.780879559                  0.578513257
ZZEF1       0.503008513                  0.301916295
ZZZ3        0.247955182                  0.216775889
            GTEX.1192X.0011.R3b.SM.GIN8Y GTEX.11DXW.0011.R3b.SM.DNZZE
A1BG        0.0440754982                 0.062893963
A1BG-AS1    0.0180885248                 0.017847235
A2M         1.7915915142                 0.746703208
A2M-AS1     0.0216687250                 0.022855020
A2ML1       0.1754240198                 0.066599797
A2MP1       0.0013885233                 0.002490928
A4GALT      0.0440882334                 0.030082108
AAAS        0.2307928940                 0.290244494
AACS        0.3744825465                 0.578171125
AACSP1      0.0006287738                 0.003325682
AADAT       0.1316765301                 0.145032696
AAGAB       0.3433133144                 0.382210784
AAK1        0.9476558616                 1.261954613
AAMDC       0.0233286549                 0.025183339
AAMP        0.7372678025                 0.680126437
AANAT       0.0040292827                 0.002660095
AAR2        0.1533132921                 0.129686648
AARD        0.0034424521                 0.012519871
AARS1       1.7103104509                 1.531353706
AARS2       0.2140579650                 0.232372194
AARSD1      0.2093711437                 0.290120842
AARSD1P1    0.0018441173                 0.001837828
AASDH       0.1109083608                 0.075406665
AASDHPPT    0.5588746668                 0.606583652
AASS        0.3434280204                 0.254127485
AATBC       0.0023667713                 0.004779431
AATF        0.1976389055                 0.162955528
AATK        1.0122545764                 1.541683083
ABAT        5.9859702699                 3.294242744
ABCA1       0.3614939884                 0.095822945
⋮           ⋮                            ⋮
ZSCAN23     0.006476213                  0.00259356
ZSCAN25     0.062912380                  0.06768457
ZSCAN26     0.131949635                  0.16305878
ZSCAN29     0.210343040                  0.10903859
ZSCAN30     0.183496451                  0.21262735
ZSCAN31     0.154374270                  0.04395530
ZSCAN32     0.105770568                  0.09986229
ZSCAN5A     0.044312788                  0.03707439
ZSCAN5A-AS1 0.003160859                  0.00380199
ZSCAN9      0.039318726                  0.03937484
ZSWIM1      0.082715789                  0.07671511
ZSWIM3      0.022853333                  0.02954240
ZSWIM4      0.015877866                  0.01368066
ZSWIM5      0.103198667                  0.08817036
ZSWIM6      0.280964471                  0.20564177
ZSWIM7      0.224449181                  0.21606709
ZSWIM8      0.559998616                  0.47887642
ZSWIM8-AS1  0.001677785                  0.00463218
ZSWIM9      0.310752429                  0.34847991
ZUP1        0.071933328                  0.06691427
ZW10        0.064502475                  0.05799363
ZWILCH      0.039247600                  0.05814915
ZWINT       0.014475443                  0.02695275
ZXDA        0.027373134                  0.01377447
ZXDB        0.082286954                  0.10165072
ZXDC        0.116498717                  0.10478871
ZYG11B      0.542973057                  0.57574692
ZYX         0.457945831                  0.69994442
ZZEF1       0.375652053                  0.42934563
ZZZ3        0.228380048                  0.19009476
            GTEX.11GS4.0011.R3b.SM.GJ3RI GTEX.11GSO.0011.R3b.SM.57WB2
A1BG        0.047815130                  0.037267769
A1BG-AS1    0.023334021                  0.027652678
A2M         1.238553992                  1.134626028
A2M-AS1     0.021212277                  0.021614851
A2ML1       0.080950591                  0.055747440
A2MP1       0.001751794                  0.002416213
A4GALT      0.034905528                  0.044716390
AAAS        0.302122441                  0.260870185
AACS        0.543457677                  0.871233188
AACSP1      0.002115720                  0.003309173
AADAT       0.152586920                  0.129334278
AAGAB       0.356950399                  0.524897647
AAK1        1.241376214                  1.875384539
AAMDC       0.027269606                  0.018659220
AAMP        0.750756650                  0.892471866
AANAT       0.005530149                  0.003895212
AAR2        0.149447306                  0.159641583
AARD        0.007914548                  0.014352092
AARS1       1.873702152                  2.665683132
AARS2       0.275594198                  0.258551175
AARSD1      0.332374036                  0.384440209
AARSD1P1    0.001916348                  0.001850131
AASDH       0.070378421                  0.074981429
AASDHPPT    0.626180874                  0.922225832
AASS        0.286714615                  0.218399725
AATBC       0.003697364                  0.005388909
AATF        0.191398571                  0.204345000
AATK        1.554100398                  1.515375421
ABAT        3.323173577                  3.393655579
ABCA1       0.149315039                  0.108660794
⋮           ⋮                            ⋮
ZSCAN23     0.002458339                  0.002863864
ZSCAN25     0.073554458                  0.077018377
ZSCAN26     0.176825983                  0.176950914
ZSCAN29     0.158534957                  0.128135452
ZSCAN30     0.307743564                  0.183659631
ZSCAN31     0.070208915                  0.059070923
ZSCAN32     0.105454534                  0.094736018
ZSCAN5A     0.026978435                  0.043897732
ZSCAN5A-AS1 0.002200207                  0.002561665
ZSCAN9      0.074852272                  0.038905143
ZSWIM1      0.083765400                  0.096858496
ZSWIM3      0.037611412                  0.046887091
ZSWIM4      0.021176300                  0.022682852
ZSWIM5      0.102558177                  0.106171258
ZSWIM6      0.242611387                  0.250962037
ZSWIM7      0.159069524                  0.226109807
ZSWIM8      0.591177055                  0.624633504
ZSWIM8-AS1  0.005328421                  0.003367994
ZSWIM9      0.212908446                  0.311681521
ZUP1        0.062575053                  0.080960537
ZW10        0.068580931                  0.084893065
ZWILCH      0.042252525                  0.067079785
ZWINT       0.028712861                  0.016560882
ZXDA        0.026853697                  0.028813819
ZXDB        0.082341167                  0.139884609
ZXDC        0.113697843                  0.097370623
ZYG11B      0.501522180                  0.840855786
ZYX         0.829150544                  0.891383282
ZZEF1       0.496780166                  0.507922558
ZZZ3        0.188879948                  0.204241426
            GTEX.11GSP.0011.R3a.SM.9QEGF GTEX.11NUK.0011.R3b.SM.GJ3RO
A1BG        0.0225745085                 0.053463744
A1BG-AS1    0.0049391977                 0.016094960
A2M         0.5811734417                 0.955865060
A2M-AS1     0.0220160579                 0.016608692
A2ML1       0.0998235693                 0.031837626
A2MP1       0.0014678241                 0.001061455
A4GALT      0.0398767973                 0.018269464
AAAS        0.2422870356                 0.261843117
AACS        0.1642607437                 0.526594072
AACSP1      0.0007548658                 0.003331557
AADAT       0.1111418839                 0.144526697
AAGAB       0.1672476964                 0.327647601
AAK1        0.3992301267                 1.020993687
AAMDC       0.0304767219                 0.027659244
AAMP        0.5804027557                 0.733888118
AANAT       0.0031783127                 0.003466126
AAR2        0.1125241918                 0.169169495
AARD        0.0025473365                 0.012126521
AARS1       1.0454945667                 1.585290021
AARS2       0.2026365109                 0.233756358
AARSD1      0.1521234523                 0.261064426
AARSD1P1    0.0012981709                 0.002261019
AASDH       0.0548457589                 0.082557795
AASDHPPT    0.2575685611                 0.633649991
AASS        0.3379640544                 0.292386303
AATBC       0.0060722444                 0.002145851
AATF        0.1719124471                 0.171981233
AATK        1.1030110100                 1.663470428
ABAT        3.0493316985                 3.417042096
ABCA1       0.1735998870                 0.155917779
⋮           ⋮                            ⋮
ZSCAN23     0.005475942                  0.005758182
ZSCAN25     0.046313379                  0.070987946
ZSCAN26     0.118678266                  0.171228415
ZSCAN29     0.111588122                  0.134853686
ZSCAN30     0.186139983                  0.199919884
ZSCAN31     0.034990666                  0.042958026
ZSCAN32     0.114802427                  0.135513810
ZSCAN5A     0.029329571                  0.043332795
ZSCAN5A-AS1 0.002572761                  0.001938458
ZSCAN9      0.044653234                  0.047444533
ZSWIM1      0.048021279                  0.085062195
ZSWIM3      0.022569604                  0.041204990
ZSWIM4      0.010782237                  0.011243815
ZSWIM5      0.068927113                  0.097115430
ZSWIM6      0.208909747                  0.271517820
ZSWIM7      0.174368360                  0.193780370
ZSWIM8      0.415079929                  0.545868673
ZSWIM8-AS1  0.004311456                  0.002671965
ZSWIM9      0.241442285                  0.248269691
ZUP1        0.029864380                  0.057999459
ZW10        0.042625551                  0.070043562
ZWILCH      0.015209816                  0.042088700
ZWINT       0.009437738                  0.023968414
ZXDA        0.023995470                  0.027379205
ZXDB        0.049955210                  0.082091440
ZXDC        0.093820134                  0.138820847
ZYG11B      0.236057219                  0.506918233
ZYX         0.391040820                  0.733705249
ZZEF1       0.306911547                  0.469035929
ZZZ3        0.159879263                  0.228826796
            GTEX.11NV4.0011.R3b.SM.GINAJ GTEX.11O72.0011.R3a.SM.H65ZL ⋯
A1BG        0.033373276                  0.0421534071                 ⋯
A1BG-AS1    0.013411110                  0.0089965235                 ⋯
A2M         1.328448682                  1.6285538562                 ⋯
A2M-AS1     0.023200338                  0.0112071203                 ⋯
A2ML1       0.024024676                  0.0713867357                 ⋯
A2MP1       0.003056557                  0.0016148609                 ⋯
A4GALT      0.015129611                  0.0801217718                 ⋯
AAAS        0.220943717                  0.2723154149                 ⋯
AACS        0.450316833                  0.3976728087                 ⋯
AACSP1      0.001191879                  0.0005850484                 ⋯
AADAT       0.150767655                  0.1232284502                 ⋯
AAGAB       0.461117313                  0.2543015313                 ⋯
AAK1        1.431672495                  0.8754288619                 ⋯
AAMDC       0.018971971                  0.0267067552                 ⋯
AAMP        0.718047053                  0.5724955738                 ⋯
AANAT       0.003815223                  0.0059027776                 ⋯
AAR2        0.130337131                  0.1306144127                 ⋯
AARD        0.014812386                  0.0034558706                 ⋯
AARS1       1.720031666                  1.3386815510                 ⋯
AARS2       0.199333444                  0.1921805838                 ⋯
AARSD1      0.315241440                  0.1931767386                 ⋯
AARSD1P1    0.002100648                  0.0009563775                 ⋯
AASDH       0.059391399                  0.0817418540                 ⋯
AASDHPPT    0.752659332                  0.4904144599                 ⋯
AASS        0.126480727                  0.3464225036                 ⋯
AATBC       0.002808599                  0.0033623146                 ⋯
AATF        0.164944265                  0.1666976208                 ⋯
AATK        1.036375279                  0.9320780240                 ⋯
ABAT        3.830475810                  3.0126114456                 ⋯
ABCA1       0.056863071                  0.2113770990                 ⋯
⋮           ⋮                            ⋮                            ⋱
ZSCAN23     0.002312757                  0.004469346                  ⋯
ZSCAN25     0.063429605                  0.040025588                  ⋯
ZSCAN26     0.146357299                  0.160350844                  ⋯
ZSCAN29     0.123919390                  0.115640498                  ⋯
ZSCAN30     0.182382729                  0.161200772                  ⋯
ZSCAN31     0.034818871                  0.036811179                  ⋯
ZSCAN32     0.090524391                  0.093620384                  ⋯
ZSCAN5A     0.035271477                  0.034634256                  ⋯
ZSCAN5A-AS1 0.002298124                  0.002311031                  ⋯
ZSCAN9      0.043807792                  0.038195668                  ⋯
ZSWIM1      0.055879482                  0.066725271                  ⋯
ZSWIM3      0.024170887                  0.021895031                  ⋯
ZSWIM4      0.018172397                  0.014474470                  ⋯
ZSWIM5      0.084188660                  0.069025156                  ⋯
ZSWIM6      0.158353093                  0.210563327                  ⋯
ZSWIM7      0.257750042                  0.150007850                  ⋯
ZSWIM8      0.405285757                  0.479928226                  ⋯
ZSWIM8-AS1  0.003616687                  0.002453687                  ⋯
ZSWIM9      0.256887877                  0.185759883                  ⋯
ZUP1        0.127511542                  0.066379819                  ⋯
ZW10        0.067635590                  0.049574817                  ⋯
ZWILCH      0.057630247                  0.040310915                  ⋯
ZWINT       0.024390596                  0.018753327                  ⋯
ZXDA        0.026231242                  0.022937050                  ⋯
ZXDB        0.093389376                  0.082869968                  ⋯
ZXDC        0.070363665                  0.085506925                  ⋯
ZYG11B      0.716940497                  0.368419289                  ⋯
ZYX         0.536542728                  0.768901822                  ⋯
ZZEF1       0.338300057                  0.376913582                  ⋯
ZZZ3        0.175503006                  0.176354726                  ⋯
            GTEX.XLM4.0011.R10A.SM.4AT5P GTEX.Y8DK.0011.R10A.SM.4SOK1
A1BG        0.046823775                  0.039194776
A1BG-AS1    0.016597189                  0.017531558
A2M         1.568130481                  1.559369011
A2M-AS1     0.025549823                  0.022783923
A2ML1       0.049662964                  0.030593333
A2MP1       0.003051612                  0.001510759
A4GALT      0.043187480                  0.037312470
AAAS        0.292685309                  0.292812709
AACS        0.559504486                  0.650464916
AACSP1      0.002161376                  0.002692578
AADAT       0.148098922                  0.118659126
AAGAB       0.441405467                  0.417483286
AAK1        1.430418713                  1.739864117
AAMDC       0.021607240                  0.012236216
AAMP        0.866559062                  0.804412959
AANAT       0.003621481                  0.004198138
AAR2        0.143070055                  0.129111620
AARD        0.007787521                  0.007862112
AARS1       2.416468755                  2.729995960
AARS2       0.210944769                  0.221498752
AARSD1      0.321845998                  0.329583914
AARSD1P1    0.001604692                  0.001506752
AASDH       0.071945215                  0.102766535
AASDHPPT    0.831370758                  0.940359643
AASS        0.304583094                  0.168482110
AATBC       0.008948338                  0.006062827
AATF        0.190691160                  0.181215536
AATK        1.875317923                  1.942969283
ABAT        3.511631022                  3.749964813
ABCA1       0.101024458                  0.079462232
⋮           ⋮                            ⋮
ZSCAN23     0.002180932                  0.003402594
ZSCAN25     0.079382143                  0.068376036
ZSCAN26     0.183318928                  0.159100620
ZSCAN29     0.143944335                  0.138561703
ZSCAN30     0.185193590                  0.154843856
ZSCAN31     0.074109323                  0.076743795
ZSCAN32     0.093696706                  0.090164616
ZSCAN5A     0.030349563                  0.028690214
ZSCAN5A-AS1 0.001425220                  0.001527976
ZSCAN9      0.057959672                  0.064223300
ZSWIM1      0.077598196                  0.074783769
ZSWIM3      0.031015664                  0.033939167