In [59]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/top_corr_module_fxns.R")

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [6]:
mod_def <- "PosBC"
unique <- FALSE

# Prep marker genes

### Claude marker genes

In [70]:
set_source <- "Claude_marker_genes"

marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_human.RDS")

### MOp pseudobulk DE genes

In [ ]:
set_source <- "yao_2021_MOp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes"

pairwise_res_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/MOp/data/DE_genes/yao_2021_MOp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")
marker_genes_list <- prep_DE_genes(pairwise_res_list, pairwise=TRUE, unique=unique)
names(marker_genes_list) <- unlist(sapply(names(marker_genes_list), function(x) gsub(" ", "_", x)))

# Convert to human markers
marker_genes_list <- lapply(marker_genes_list, function(gene_list) {
    convert_genes(gene_list, target_species="human")
})

### ACA pseudobulk DE genes

In [63]:
set_source <- "yao_2021_ACA_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes"

pairwise_res_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA/data/DE_genes/yao_2021_ACA_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")
marker_genes_list <- prep_DE_genes(pairwise_res_list, lfc_threshold, pairwise=TRUE, unique=unique)

# Convert to human markers
marker_genes_list <- lapply(marker_genes_list, function(gene_list) {
    convert_genes(gene_list, target_species="human")
})

### MO marker genes

In [3]:
# load("/mnt/lareaulab/reliscu/data/gene_sets/Oldham/MO_sets.RData")

In [4]:
# sets <- c(
#     "BARRES_ASTROCYTES",
#     "BARRES_OLIGODENDROCYTES",
#     "HICKMAN_MICROGLIA_SENSOME_99",
#     "BARRES_NEURONS",
#     "BUTLER_ENDOTHELIAL_HPA",
#     "ZEISEL_MURAL",
#     "ZEISEL_EPENDYMAL",
#     "ZEISEL_INTERNEURON",
#     "ZHANG_MOUSE_OPC_2014",
#     "Mukamel_InhibitoryNeurons",
#     "Mukamel_ExcitatoryNeurons",
#     "SUGINO_UP_GABAERGIC_NEURONS",
#     "SUGINO_UP_GLUTAMATERGIC_NEURONS",
#     "SUGINO_UP_LAYERS4-6_GABAERGIC_NEURONS_CINGULATE_CTX",
#     "BAKKEN_2019_PVALB_GABAERGIC_DE_GABA_CLUSTERS",
#     "BAKKEN_2019_VIP_GABAERGIC_DE_GABA_CLUSTERS",
#     "BAKKEN_2019_SST_GABAERGIC_DE_GABA_CLUSTERS",
#     "BAKKEN_2019_LAMP5_GABAERGIC_DE_GABA_CLUSTERS",
#     "BAKKEN_2019_SNCG_GABAERGIC_DE_GABA_CLUSTERS",
#     "BAKKEN_2019_SST_CHODL_GABAERGIC_DE_GABA_CLUSTERS",
#     "VELMESHEV_2019_IN_SST",
#     MO_legend$SetName[grepl("schirmer", MO_legend$SetName, ignore.case=T)],
#     MO_legend$SetName[grepl("yang_pfc", MO_legend$SetName, ignore.case=T)]
# )

In [5]:
# mask <- MO_legend$SetName %in% sets

# marker_genes_list <- MO_sets[mask]
# names(marker_genes_list) <- MO_legend$SetName[mask] 

# marker_genes_list <- lapply(marker_genes_list, toupper)

### Gugene DE genes

In [4]:
marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/kang_2026_preprint/kang_2026_preprint_DE_genes.RData")

In [ ]:
marker_genes_list1 <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/kang_2026_preprint/kang_2026_preprint_Jorstad_2023_DE_genes.RData")
marker_genes_list2 <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/kang_2026_preprint/kang_2026_preprint_Gabitto_2024_DE_genes.RData")

marker_genes_list <- lapply(seq_along(marker_genes_list1), function(i) {
    union(marker_genes_list1[[i]], marker_genes_list2[[i]])
})

names(marker_genes_list) <- names(marker_genes_list1)

# Get enrichments

### TPM data

In [51]:
network_dir <- "GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules"

In [71]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [74]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [75]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type Pval         Qval         Module
1  Pvalb     1.653881e-27 4.258743e-23 plum2
2  Sst       6.467972e-27 5.102260e-23 plum2
3  Sst Chodl 6.747673e-25 1.241090e-21 darkgreen
4  Vip       2.109779e-24 3.195694e-21 lightcyan
5  Micro/PVM 4.172165e-24 5.654381e-21 skyblue
6  Pax6      2.391264e-19 9.773818e-17 greenyellow
7  Oligo     6.058142e-19 2.197143e-16 tan
8  Astro     7.173324e-19 2.530316e-16 mediumorchid
9  VLMC      1.183773e-12 1.870070e-10 white
10 L2/3 IT   3.171216e-12 4.747606e-10 yellow
11 L6b       5.180407e-09 5.676404e-07 blue
12 L5 ET     6.753778e-09 7.307134e-07 black
13 L6 CT     3.434998e-08 3.509969e-06 white
14 Peri      5.431318e-07 4.773258e-05 indianred4
15 Endo      7.984402e-07 6.830510e-05 lightpink4
16 OPC       1.976212e-06 1.585279e-04 paleturquoise
   Network
1  Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277
2  Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277
3  Bicor-None_signum0.843_minSize6_merge_ME_0.95_22277
4  Bicor-None_signum0.843_minSize8_merge_ME_0.95_22277
5  Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277
6  Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277
7  Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277
8  Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277
9  Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277
10 Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277
11 Bicor-None_signum0.969_minSize4_merge_ME_0.95_22277
12 Bicor-None_signum0.93_minSize6_merge_ME_0.95_22277
13 Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277
14 Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277
15 Bicor-None_signum0.82_minSize8_merge_ME_0.95_22277
16 Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277

In [76]:
get_mod_vs_DE_genes(top_mods_df, marker_genes_list, mod_def)

          Cell_type Qval
Pvalb     Pvalb     4.258743e-23
Sst       Sst       5.102260e-23
Sst Chodl Sst Chodl 1.241090e-21
Vip       Vip       3.195694e-21
Micro/PVM Micro/PVM 5.654381e-21
Pax6      Pax6      9.773818e-17
Oligo     Oligo     2.197143e-16
Astro     Astro     2.530316e-16
VLMC      VLMC      1.870070e-10
L2/3 IT   L2/3 IT   4.747606e-10
L6b       L6b       5.676404e-07
L5 ET     L5 ET     7.307134e-07
L6 CT     L6 CT     3.509969e-06
Peri      Peri      4.773258e-05
Endo      Endo      6.830510e-05
OPC       OPC       1.585279e-04
          Module_genes
Pvalb     ZNF385D, GAD2, GAD1, MYO5B, LGI2, KCNS3, NXPH2, VWC2, BTBD11, NXPH1, TACR1, LHX6, SLC32A1, MINAR1, ARL4C
Sst       ZNF385D, GAD2, GAD1, MYO5B, LGI2, KCNS3, NXPH2, VWC2, BTBD11, NXPH1, TACR1, LHX6, SLC32A1, MINAR1, ARL4C
Sst Chodl ZNF385D, GAD2, GAD1, MYO5B, LGI2, KCNS3, NXPH2, VWC2, BTBD11, NXPH1, TACR1, LHX6, SLC32A1, MINAR1, ARL4C
Vip       ZNF385D, GAD2, GAD1, MYO5B, LGI2, KCNS3, NXPH2, VWC2, BTBD11, NXPH1, TACR1, LHX6, SLC32A1, MINAR1, ARL4C
Micro/PVM ITGB2, C1QC, C1QA, LAIR1, C1QB, SPI1, LAPTM5, CD300A, SASH3, TBXAS1, NCKAP1L, LAT2, HCK, TYROBP, ALOX5AP
Pax6      ZNF385D, GAD2, GAD1, MYO5B, LGI2, KCNS3, NXPH2, VWC2, BTBD11, NXPH1, TACR1, LHX6, SLC32A1, MINAR1, ARL4C
Oligo     CNP, MOG, FA2H, ELOVL1, NIPAL4, MAG, TRIM59, SLC45A3, ERBB3, TMEM125, FRMD4B, DBNDD2, PLLP, PLPP2, CNTN2
Astro     PLPP3, SLC39A12, BMPR1B, METTL7A, SPON1, MSI2, SLC1A3, GJA1, SDC2, S1PR1, RANBP3L, GRAMD1C, ZNRF3, PON2, GABRG1
VLMC      DSP, FAM20A, PTGDR, STRA6, FOXD2, SERPIND1, SIX1, SLC13A4, SLC6A20, SLC47A1, FMOD, BMP5, GJB2, BNC2, SLC5A5
L2/3 IT   ATCAY, MADD, SCAMP5, NUDCD3, NICN1, MAPT, TBC1D25, SYNGR1, GSK3A, PGBD5, ATP6V0A1, SYT7, GALNT17, UBL4A, PTPN5
L6b       AP2M1, ATP6V0D1, ACOT7, OTUB1, FARSA, HMOX2, MDH2, ATP6V0A1, NAPA, GDI1, BSCL2, USP5, DCTN2, SCAMP5, RETREG2
L5 ET     PGM2L1, PAK3, GDA, RAB3C, RAB27B, SLC26A4-AS1, ERC2, NECAP1, PPM1E, FAM102B, TUSC3, YWHAB, ATP6V1A, YWHAZ, NEXMIF
L6 CT     KIFAP3, MAP1B, SYT1, RTN3, ATP6V1B2, PCLO, KLC1, MAPK9, WDR7, DCLK1, INPP5F, GPRASP2, CADPS, CDK14, MAP2K4
Peri      ACTA2, MYL9, JPH2, MYH11, CASQ2, AOC3, ITIH3, PLN, COL14A1, TAGLN, KCNMB1, FHL5, ENSG00000253123, CNN1, CPED1
Endo      C1QC, C1QB, LAIR1, C1QA, ITGB2, SPI1, CD300A, HCK, SASH3, SNX20, FCER1G, ABI3, HCLS1, FCGR3A, LAPTM5
OPC       MAG, CNP, FA2H, NINJ2, PLLP, ELOVL1, GJB1, TMEM125, GPR62, KLK6, RNASE1, PLPP2, MOG, DBNDD2, NIPAL4
          DE_genes
Pvalb     GAD1, GAD2, LHX6, PVALB, SLC32A1, DLX1, DLX2, DLX5, ERBB4, KCNC1, MYO5B, NKX2-1, RBFOX3, SOX6, SYT2
Sst       GAD1, GAD2, LHX6, SLC32A1, SST, CALB1, CALB2, CBLN4, CHRNA2, DLX1, DLX2, DLX5, ETV1, HPSE, MYH8
Sst Chodl CHODL, GAD1, GAD2, LHX6, SLC32A1, SST, DLX1, DLX2, DLX5, NKX2-1, NOS1, NPY, RBFOX3, SOX6, TACR1
Vip       ADARB2, GAD1, GAD2, SLC32A1, VIP, CALB2, CHAT, CRH, DLX1, DLX2, DLX5, GPC3, HTR3A, MYBPC1, NR2F2
Micro/PVM CTSS, CX3CR1, ITGAM, P2RY12, TMEM119, TYROBP, AIF1, C1QA, C1QB, C1QC, CSF1R, HEXB, SALL1, SPI1, TREM2
Pax6      ADARB2, GAD1, GAD2, PAX6, SLC32A1, DLX1, DLX2, DLX5, HTR3A, NPY, NR2F2, PROX1, RBFOX3, RELN, DLX6
Oligo     MBP, MOG, PLP1, CLDN11, CNP, ERMN, MAG, MOBP, OPALIN, ENPP6, FA2H, KLK6, TF, UGT8A, NA
Astro     ALDH1L1, AQP4, GFAP, SLC1A2, SLC1A3, ALDOC, FGFR3, GJA1, GLUL, NDRG2, S100B, SOX9, ACSL6, AGT, APOE
VLMC      COL1A1, COL1A2, DCN, LUM, CD44, COL3A1, IL33, OGN, PTGDS, SLC6A13, SPP1, NA, NA, NA, NA
L2/3 IT   CUX2, LINC00507, SLC17A7, CAMK2A, CUX1, MDGA1, OTOF, RASGRF2, RBFOX3, SATB2, TBR1, EMX1, ENO2, LAMP5, MAP2
L6b       CCN2, NXPH4, SLC17A7, CAMK2A, CPLX3, INPP4B, OR2T8, RBFOX3, RGS12, SERPINB11, TBR1, TRH, EMX1, ENO2, MAP2
L5 ET     BCL11B, BCL6, FAM84B, FEZF2, SLC17A7, CAMK2A, CDH13, CHRNA6, CRYM, NNAT, NPNT, POU3F1, RBFOX3, SLC17A6, TBR1
L6 CT     FOXP2, SLC17A7, SYT6, CAMK2A, NTNG2, NXPH2, RBFOX3, TBR1, TLE4, EMX1, ENO2, MAP2, NEUROD2, NEUROD6, NRGN
Peri      ABCC9, KCNJ8, PDGFRB, ANPEP, CSPG4, MCAM, NOTCH3, RGS5, VTN, DES, DLK1, NA, NA, NA, NA
Endo      CLDN5, FLT1, EMCN, NOSTRIN, PECAM1, SLCO1A4, TEK, VWF, BSG, ITM2A, LY6C1, NA, NA, NA, NA
OPC       CSPG4, PDGFRA, GPR17, NKX2-2, OLIG1, OLIG2, SOX10, VCAN, BCAN, PCDH15, PTPRZ1, NA, NA, NA, NA
          Intersection_genes
Pvalb     GAD1,GAD2,LHX6,SLC32A1,DLX1,ERBB4,MYO5B,TAC1,DLX6,KCNC2,MAP2,PTHLH,STMN2
Sst       GAD1,GAD2,LHX6,SLC32A1,DLX1,DLX6,MAFB,MAP2,STMN2
Sst Chodl GAD1,GAD2,LHX6,SLC32A1,DLX1,TACR1,DLX6,MAFB,MAP2,STMN2
Vip       GAD1,GAD2,SLC32A1,DLX1,DLX6,MAP2,STMN2
Micro/PVM CTSS,CX3CR1,ITGAM,TMEM119,TYROBP,AIF1,C1QA,C1QB,C1QC,CSF1R,SPI1,TREM2
Pax6      GAD1,GAD2,SLC32A1,DLX1,DLX6,MAP2,STMN2
Oligo     MOG,PLP1,CLDN11,CNP,ERMN,MAG,OPALIN,FA2H,KLK6,TF
Astro     AQP4,SLC1A2,SLC1A3,FGFR3,GJA1,GLUL,SOX9,AGT,APOE
VLMC      COL1A1,COL1A2,DCN,COL3A1,OGN,PTGDS,SLC6A13
L2/3 IT
L6b       ENO2,THY1
L5 ET     CDH13,STMN2,SYT1
L6 CT     ENO2,SNAP25,STMN2,SYT1
Peri      MCAM,NOTCH3,DES
Endo
OPC       SOX10
          Module        Network
Pvalb     plum2         Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277
Sst       plum2         Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277
Sst Chodl darkgreen     Bicor-None_signum0.843_minSize6_merge_ME_0.95_22277
Vip       lightcyan     Bicor-None_signum0.843_minSize8_merge_ME_0.95_22277
Micro/PVM skyblue       Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277
Pax6      greenyellow   Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277
Oligo     tan           Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277
Astro     mediumorchid  Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277
VLMC      white         Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277
L2/3 IT   yellow        Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277
L6b       blue          Bicor-None_signum0.969_minSize4_merge_ME_0.95_22277
L5 ET     black         Bicor-None_signum0.93_minSize6_merge_ME_0.95_22277
L6 CT     white         Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277
Peri      indianred4    Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277
Endo      lightpink4    Bicor-None_signum0.82_minSize8_merge_ME_0.95_22277
OPC       paleturquoise Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277
          ME_path
Pvalb     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277/Module_eigengenes_01-44-19.csv
Sst       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277/Module_eigengenes_02-05-47.csv
Sst Chodl /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize6_merge_ME_0.95_22277/Module_eigengenes_11-59-44.csv
Vip       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize8_merge_ME_0.95_22277/Module_eigengenes_12-20-19.csv
Micro/PVM /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277/Module_eigengenes_01-20-31.csv
Pax6      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277/Module_eigengenes_12-27-13.csv
Oligo     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277/Module_eigengenes_02-05-47.csv
Astro     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277/Module_eigengenes_12-34-58.csv
VLMC      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277/Module_eigengenes_01-44-19.csv
L2/3 IT   /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277/Module_eigengenes_12-27-13.csv
L6b       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.969_minSize4_merge_ME_0.95_22277/Module_eigengenes_10-46-15.csv
L5 ET     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.93_minSize6_merge_ME_0.95_22277/Module_eigengenes_11-09-52.csv
L6 CT     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277/Module_eigengenes_01-20-31.csv
Peri      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277/Module_eigengenes_12-34-58.csv
Endo      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize8_merge_ME_0.95_22277/Module_eigengenes_12-53-25.csv
OPC       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277/Module_eigengenes_12-34-58.csv
          kME_path
Pvalb     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277/kME_table_01-44-19.csv
Sst       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277/kME_table_02-05-47.csv
Sst Chodl /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize6_merge_ME_0.95_22277/kME_table_11-59-44.csv
Vip       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize8_merge_ME_0.95_22277/kME_table_12-20-19.csv
Micro/PVM /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277/kME_table_01-20-31.csv
Pax6      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277/kME_table_12-27-13.csv
Oligo     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize10_merge_ME_0.95_22277/kME_table_02-05-47.csv
Astro     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277/kME_table_12-34-58.csv
VLMC      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize8_merge_ME_0.95_22277/kME_table_01-44-19.csv
L2/3 IT   /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.843_minSize10_merge_ME_0.95_22277/kME_table_12-27-13.csv
L6b       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.969_minSize4_merge_ME_0.95_22277/kME_table_10-46-15.csv
L5 ET     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.93_minSize6_merge_ME_0.95_22277/kME_table_11-09-52.csv
L6 CT     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.8_minSize6_merge_ME_0.95_22277/kME_table_01-20-31.csv
Peri      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277/kME_table_12-34-58.csv
Endo      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize8_merge_ME_0.95_22277/kME_table_12-53-25.csv
OPC       /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_TPM_All_598_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.26_Modules/Bicor-None_signum0.82_minSize6_merge_ME_0.95_22277/kME_table_12-34-58.csv

In [77]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

### Counts data

In [26]:
network_dir <- "GTEx_cortex_counts_rd2_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules"

In [ ]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [ ]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type  Pval          Qval          Module
1  Astro      4.432476e-112 3.892423e-107 green
2  Micro/PVM   4.465014e-85  1.960498e-80 ivory
3  Oligo       2.508114e-73  3.670876e-69 pink
4  Endo        9.136950e-37  3.086040e-33 lightgoldenrodyellow
5  VLMC        1.723223e-28  4.323616e-25 antiquewhite1
6  OPC         3.363768e-16  3.009703e-13 grey60
7  L2/3 IT     9.579135e-13  6.421384e-10 plum1
8  L4 IT       4.493806e-10  2.110310e-07 darkgreen
9  L5 ET       7.021306e-09  2.680796e-06 goldenrod1
10 Pvalb       1.637498e-08  5.683735e-06 wheat1
11 L6 IT Car3  1.239443e-07  3.616043e-05 mintcream
12 L6b         1.157988e-05  2.109748e-03 deeppink4
13 Chandelier  1.684628e-05  2.964676e-03 brown4
14 Sst Chodl   2.150169e-05  3.652209e-03 steelblue3
15 L5 IT       4.539988e-05  7.081414e-03 indianred4
16 L6 CT       4.526603e-05  7.081414e-03 gray29
17 Lamp5 Lhx6  5.907660e-05  8.929209e-03 honeydew3
18 Sncg        8.568204e-05  1.235413e-02 sandybrown
19 L6 IT       9.430085e-05  1.342159e-02 hotpink4
20 Vip         1.021226e-04  1.430303e-02 salmon2
21 L5/6 NP     3.417069e-04  3.881932e-02 gray11
22 Sst         2.603736e-03  1.843949e-01 mediumorchid2
   Network
1  Bicor-None_signum0.898_minSize6_merge_ME_0.95_22174
2  Bicor-None_signum0.898_minSize3_merge_ME_0.95_22174
3  Bicor-None_signum0.82_minSize10_merge_ME_0.95_22174
4  Bicor-None_signum0.665_minSize8_merge_ME_0.95_22174
5  Bicor-None_signum0.665_minSize10_merge_ME_0.95_22174
6  Bicor-None_signum0.82_minSize8_merge_ME_0.95_22174
7  Bicor-None_signum0.82_minSize6_merge_ME_0.95_22174
8  Bicor-None_signum0.82_minSize8_merge_ME_0.95_22174
9  Bicor-None_signum0.898_minSize2_merge_ME_0.95_22174
10 Bicor-None_signum0.665_minSize6_merge_ME_0.95_22174
11 Bicor-None_signum0.541_minSize6_merge_ME_0.95_22174
12 Bicor-None_signum0.82_minSize3_merge_ME_0.95_22174
13 Bicor-None_signum0.898_minSize3_merge_ME_0.95_22174
14 Bicor-None_signum0.665_minSize6_merge_ME_0.95_22174
15 Bicor-None_signum0.541_minSize6_merge_ME_0.95_22174
16 Bicor-None_signum0.593_minSize6_merge_ME_0.95_22174
17 Bicor-None_signum0.82_minSize3_merge_ME_0.95_22174
18 Bicor-None_signum0.593_minSize6_merge_ME_0.95_22174
19 Bicor-None_signum0.665_minSize6_merge_ME_0.95_22174
20 Bicor-None_signum0.665_minSize10_merge_ME_0.95_22174
21 Bicor-None_signum0.593_minSize6_merge_ME_0.95_22174
22 Bicor-None_signum0.593_minSize8_merge_ME_0.95_22174

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)