In [2]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/top_corr_module_fxns.R")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: future


Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths



Attaching package: ‘data.table’


The following objects are masked from ‘package:reshape2’:

    dcast, melt


The following objects are masked from ‘package:dplyr’:

    between, first, last

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [ ]:
n_workers <- 20
mod_def <- "PosBC"
max_set_size <- 200
min_set_size <- 3

## Prep marker genes

### Claude marker genes

In [3]:
set_source <- "Claude_marker_genes"

marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_human.RDS")

### Broad

In [ ]:
library(msigdbr)

In [ ]:
gs_GOBP <- msigdbr(collection="C5", subcollection="GO:BP")

gs_CTS <- msigdbr(collection="C8")
gs_CTS <- gs_CTS[gs_CTS$gs_geoid == "GSE104276",]

gs_GOBP_list <- tapply(gs_GOBP$gene_symbol, INDEX=gs_GOBP$gs_name, FUN=list)
gs_CTS_list <- tapply(gs_CTS$gene_symbol, INDEX=gs_CTS$gs_name, FUN=list)

gs_list <- c(gs_GOBP_list, gs_CTS_list)

In [ ]:
set_sizes <- lengths(gs_list)
mask <- (set_sizes < max_set_size) & (set_sizes > min_set_size)
gs_list <- gs_list[mask]

print(length(gs_list))

In [ ]:
marker_genes_list <- gs_list

In [ ]:
set_source <- paste0("MSigDB_", length(gs_list), "sets")

### MO marker genes

In [ ]:
load("/mnt/lareaulab/reliscu/data/gene_sets/Oldham/MO_sets.RData")

mask <- !MO_legend$Category %in% "Disease"
marker_genes_list <- MO_sets[mask]
names(marker_genes_list) <- MO_legend$SetName[mask]

set_sizes <- lengths(marker_genes_list)
mask <- (set_sizes < max_set_size) & (set_sizes > min_set_size)
marker_genes_list <- marker_genes_list[mask]

print(length(marker_genes_list))

set_source <- paste0("MO_", length(marker_genes_list), "sets")

## Get enrichments

In [ ]:
network_dir <- "GTEx_cortex_counts_All_501_outliers_removed_TMM_ComBat_SMGEBTCH_corrected_All_370_outliers_removed_mergeParam0.95_subsetCutoff11.245_Modules"

In [ ]:
enrichments_df <- get_module_enrichments_par(network_dir, marker_genes_list, mod_def, n_workers)

write.csv(enrichments_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)
    
# top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

# get_mod_vs_DE_genes(top_mods_df, marker_genes_list, mod_def)

write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments_top_Qval_mods.csv"), row.names=FALSE, quote=FALSE)

## Compare enrichments

In [5]:
x <- list.files("data/enrichments")[grep("Qval", list.files("data/enrichments"))]
x <- x[grep("MO", x)]

enrichments_list <- lapply(x, function(y) {
    split <- unlist(strsplit(y, "STAR_"))
    prefix <- unlist(strsplit(split[1], "_ComBat"))[1]
    middle <- gsub("p_", "p", unlist(strsplit(split[1], "yao_2021_"))[2])
    suffix <- gsub("_enrichments.csv", "", unlist(strsplit(split[2], "DE_genes_"))[2])
    dataname <- paste(prefix, paste(middle, suffix, sep="_"), sep="_")

    enrich_df <- fread(file.path("data/enrichments", y), data.table=FALSE)
    enrich_df <- enrich_df[,c("Cell_type", "Qval")]
    colnames(enrich_df)[2] <- dataname
    enrich_df
})

enrichment_table <- Reduce(f=function(x, y) {
    merge(x, y, by="Cell_type", all=TRUE)
}, enrichments_list)

Warning message in fread(file.path("data/enrichments", y), data.table = FALSE):
“Previous fread() session was not cleaned up properly. Cleaned up ok at the beginning of this fread() call.”

In [6]:
enrichment_table

    Cell_type
1   ABA_ASTROCYTES
2   ABA_NEURONS
3   ABSINTA_2021_MS_OPC_DE_OG_CLUSTERS
4   ABSINTA_2021_PLASMABLASTS_DE_MG_CLUSTERS
5   ABSINTA_2021_VASCULAR_UNKNOWN_DE_VASC_CLUSTERS
6   AGARWAL_CTX_2020_IN1A_DE_IN_CLUSTERS
7   AGARWAL_CTX_2020_IN1B
8   AGARWAL_CTX_2020_IN4A_DE_IN_CLUSTERS
9   AGARWAL_SN_2020_ASTROCYTES_2_DE_ASC_CLUSTERS
10  AGARWAL_SN_2020_ENDOTHELIAL
11  Anatol_mouse_D1_MSN_vs_striatum_dropviz
12  Anatol_mouse_D1_MSN-1_vs_striatum_dropviz
13  Anatol_mouse_D1_MSN-3_vs_striatum_dropviz
14  Anatol_mouse_D1_MSN-patch_vs_striatum_dropviz
15  Anatol_mouse_D2_MSN_vs_striatum_dropviz
16  Anatol_mouse_D2_MSN-2_vs_striatum_dropviz
17  Anatol_mouse_PV_vs_striatum_dropviz
18  ARAI_E14.5_TIS21-GFP+_S-PHASE_BASAL_PROGENITORS
19  AYHAN_2021_GRA_NEU7_DE_NEU_CLUSTERS
20  BAKHTIAR_PHENOCOPY_EGFR
21  BAKHTIAR_PHENOCOPY_PARP_HRD
22  BAKHTIAR_PHENOCOPY_PI3K_AKT
23  BAKKEN_2019_EXC_L2_3_RORB_PTPN3
24  BAKKEN_2019_EXC_L2_3_RORB_RTKN2
25  BAKKEN_2019_EXC_L3_5_RORB_LAMA4
26  BAKKEN_2019_EXC_L3_5_RORB_LINC01202
27  BAKKEN_2019_EXC_L3_THEMIS_ENPEP
28  BAKKEN_2019_EXC_L5_6_FEZF2_FILIP1L
29  BAKKEN_2019_EXC_L5_6_FEZF2_SH2D1B
30  BAKKEN_2019_EXC_L5_6_THEMIS_TNFAIP6
⋮   ⋮
494 TRAN_NAC_2020_MSN_D1_C
495 TRAN_NAC_2020_MSN_D1_C_DE_PAIRWISE
496 TRAN_NAC_2020_MSN_D1_D_DE_PAIRWISE
497 TRAN_NAC_2020_MSN_D1_E_DE_PAIRWISE
498 TRAN_NAC_2020_MSN_D2_A_DE_PAIRWISE
499 TRAN_NAC_2020_OPC
500 VELMESHEV_2019_IN_SST
501 VELMESHEV_2019_NEU_MAT
502 WATKINS_CD14+_MONOCYTES
503 WATKINS_CD8+_CYTOTOXIC_T_CELLS
504 YANG_2021_ARTERIAL_DE_BEC_CLUSTERS
505 YANG_2021_BEC_ARTERIAL
506 YANG_2021_BEC_CAPILLARY
507 YANG_2021_BEC_VENOUS
508 YANG_2021_CAPILLARY_DE_BEC_CLUSTERS
509 YANG_2021_DURAL_DE_FIBRO_CLUSTERS
510 YANG_2021_MACROPHAGE_MICROGLIA
511 YANG_2021_MENINGEAL_FIBROBLAST
512 YANG_2021_NEURON
513 YANG_2021_PROTEOSTATIC_DE_BEC_CLUSTERS
514 YANG_2021_SMC
515 YANG_2021_SMC_DE_MURAL_CLUSTERS
516 YANG_CP_2021_EPITHELIAL
517 YANG_CP_2021_GPX3_EPITHELIAL
518 YANG_CP_2021_MT_EPITHELIAL
519 ZENG_HUMAN_INTERNEURON_MARKERS
520 ZENG_HUMAN_NEOCORTEX_LAYER_VI_MARKERS
521 ZHANG_MOUSE_ENDOTHELIAL_2014
522 ZHANG_MOUSE_MICROGLIA_2014
523 ZHANG_MOUSE_NEURONS_2014
    GTEx_cortex_counts_All_501_outliers_removed_TMM_NA_NA
1   1.133512e-11
2             NA
3   2.207872e-03
4   2.441422e-13
5             NA
6   1.975611e-21
7   5.745537e-53
8             NA
9             NA
10            NA
11  7.539216e-03
12            NA
13            NA
14  3.331135e-02
15  3.282889e-03
16  3.513562e-02
17  1.645633e-08
18            NA
19  1.515805e-57
20  4.101409e-03
21  7.789307e-07
22  5.986926e-04
23  1.353915e-01
24  9.009653e-02
25  1.301028e-01
26  1.000000e+00
27  1.301028e-01
28            NA
29  1.432201e-01
30  1.822364e-01
⋮   ⋮
494  3.597692e-06
495  2.321771e-02
496  5.459327e-03
497  1.253436e-07
498  1.712783e-06
499  3.319799e-26
500  4.574035e-29
501            NA
502            NA
503  1.049586e-01
504  1.947970e-11
505  3.548996e-14
506  1.331849e-27
507  3.007734e-17
508            NA
509  3.010045e-12
510  6.084787e-84
511  7.862169e-44
512 1.123803e-113
513            NA
514  1.041121e-54
515  8.370906e-38
516            NA
517  6.157542e-33
518  2.595090e-26
519            NA
520  5.049545e-03
521  1.042017e-20
522            NA
523            NA
    GTEx_cortex_counts_TMMF_All_501_outliers_removed_mergeParam0.95_subsetCutoff10.171_Modules_MO_1271sets_enrichments_top_Qval_mods.csv_NA_NA
1   3.678944e-14
2   6.930343e-18
3             NA
4             NA
5   1.132847e-42
6   3.607504e-29
7             NA
8   7.707139e-16
9   6.481391e-09
10  3.632174e-46
11            NA
12  1.060170e-02
13  6.201159e-03
14            NA
15  2.657094e-02
16            NA
17            NA
18  8.121442e-03
19            NA
20            NA
21  2.810186e-11
22  2.320090e-03
23  7.590164e-02
24  1.888356e-01
25  9.870650e-02
26            NA
27  1.038333e-01
28  1.186965e-01
29  1.598728e-01
30            NA
⋮   ⋮
494 8.839196e-05
495           NA
496           NA
497           NA
498           NA
499           NA
500           NA
501 1.482416e-63
502 3.027226e-21
503           NA
504           NA
505           NA
506           NA
507 4.315607e-34
508 7.237742e-11
509           NA
510           NA
511 5.711726e-13
512           NA
513 1.809072e-10
514           NA
515           NA
516 8.334464e-04
517           NA
518 6.116076e-23
519 3.656938e-44
520           NA
521           NA
522 8.326425e-92
523 1.041698e-30

In [7]:
data.frame(colMeans(enrichment_table[,-1], na.rm=TRUE))

                                                                                                                                           colMeans.enrichment_table....1...na.rm...TRUE.
GTEx_cortex_counts_All_501_outliers_removed_TMM_NA_NA                                                                                      0.05566010
GTEx_cortex_counts_TMMF_All_501_outliers_removed_mergeParam0.95_subsetCutoff10.171_Modules_MO_1271sets_enrichments_top_Qval_mods.csv_NA_NA 0.04592989