In [21]:
import sys
import numpy as np

sys.path.append("/mnt/lareaulab/reliscu/code")

from parse_gtf import *

## Get module eigengenes for cell types of interest

In [22]:
top_mods_df1 = pd.read_csv("data/enrichments/GTEx_cortex_counts_TMMF_All_501_outliers_removed_mergeParam0.95_subsetCutoff10.171_Modules_MO_1271sets_enrichments_top_Qval_mods.csv")

ctypes = [
    "kelley_microglia", "kelley_astro", "VELMESHEV_2019_NEU_MAT?", "JAKEL_2019_OLIGODENDROCYTE3", "LUO_2019_ASTRO_FGF3R_CABLES1_DE_GLIAL_CLUSTERS",
    "TRAN_DLPFC_2020_OPC", "TRAN_DLPFC_2020_EXCIT_A", "TRAN_DLPFC_2020_EXCIT_B", "TRAN_AMY_2020_INHIB_B_DE_PAIRWISE"
]


top_mods_df1 = top_mods_df1[top_mods_df1['Cell_type'].isin(ctypes)]

In [23]:
top_mods_df2 = pd.read_csv("data/enrichments/GTEx_cortex_counts_TMMF_All_501_outliers_removed_mergeParam0.95_subsetCutoff10.171_Modules_Claude_marker_genes_enrichments_top_Qval_mods.csv")

ctypes = [
    "Micro/PVM", "Oligo", "Astro", "Endo", "CGE Class"
]

top_mods_df2 = top_mods_df2[top_mods_df2['Cell_type'].isin(ctypes)]

In [74]:
top_mods_df2[top_mods_df2['Cell_type'] == "Astro"]['Module'].item()

'sienna3'

In [24]:
top_mods_df3 = pd.read_csv("data/enrichments/GTEx_cortex_counts_TMMF_All_501_outliers_removed_47840genes_cleaned_44846genes_cleaned_mergeParam0.85_subsetCutoff1.427_Modules_MO_1117sets_enrichments_top_Qval_mods.csv")

ctypes = [
    "kelley_Endothelial", "kelley_oligo", "AGARWAL_CTX_2020_OPC", "BARRES_ASTROCYTES", 
    "ZENG_HUMAN_INTERNEURON_MARKERS", "LaMANNO_PERICYTE_MIDBRAIN", "YANG_PFC_2021_L4_EXCITATORY_NEURON"
]

top_mods_df3 = top_mods_df3[top_mods_df3['Cell_type'].isin(ctypes)]

In [72]:
top_mods_df3[top_mods_df3['Cell_type'] == "BARRES_ASTROCYTES"]['Module'].item()

'brown'

In [25]:
top_mods_df4 = pd.read_csv("data/enrichments/GTEx_cortex_counts_TMMF_All_501_outliers_removed_47840genes_cleaned_44846genes_cleaned_mergeParam0.85_subsetCutoff1.427_Modules_Claude_marker_genes_enrichments_top_Qval_mods.csv")

ctypes = [
    "All GABAergic", "VLMC", "All Neuronal", "L2/3 IT", "Peri", "L6 IT"
]

top_mods_df4 = top_mods_df4[top_mods_df4['Cell_type'].isin(ctypes)]

In [27]:
top_mods_df = pd.concat([top_mods_df1, top_mods_df2, top_mods_df3, top_mods_df4], axis=0)
top_mods_df.head()

,Network,kME_path,ME_path,Pval,Cell_type,Module,Qval
0,Bicor-None_signum0.768_minSize10_merge_ME_0.95...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,5.578554e-232,kelley_microglia,navajowhite2,7.973090e-226
1,Bicor-None_signum0.891_minSize4_merge_ME_0.95_...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,2.583089e-210,kelley_astro,sienna3,1.476741e-204
11,Bicor-None_signum0.768_minSize10_merge_ME_0.95...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,1.085430e-65,JAKEL_2019_OLIGODENDROCYTE3,plum1,1.915234e-61
20,Bicor-None_signum0.809_minSize10_merge_ME_0.95...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,1.284826e-51,LUO_2019_ASTRO_FGF3R_CABLES1_DE_GLIAL_CLUSTERS,darkgrey,1.093050e-47
31,Bicor-None_signum0.809_minSize6_merge_ME_0.95_...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,/mnt/lareaulab/reliscu/projects/NSF_GRFP/analy...,1.029044e-40,TRAN_DLPFC_2020_OPC,darkseagreen2,3.953630e-37

In [28]:
results = []
for idx, row in top_mods_df.iterrows():
    modEig = pd.read_csv(row['ME_path'], index_col=0)[row['Module']]
    modEig.name = row['Cell_type']
    results.append(modEig)
    
ctype_abund_df = pd.concat(results, axis=1)

In [ ]:
ctype_abund_df.to_csv("data/ctype_abundance/GTEx_cortex_counts_TMMF_All_501_outliers_removed_top_Qval_mods_PC1_ctype_abundance.csv")

# Gene expr

In [47]:
bulk_expr = pd.read_csv("GTEx_cortex_counts_TMMF_SampleNetworks/All_02-25-12/GTEx_cortex_counts_TMMF_All_501_outliers_removed.csv")
bulk_expr.columns.values[0] = "Gene"

In [48]:
bulk_expr.head()

,Gene,GTEX.111FC.0011.R3b.SM.GJ3PN,GTEX.117XS.0011.R3a.SM.GIN8W,GTEX.1192X.0011.R3b.SM.GIN8Y,GTEX.11DXW.0011.R3b.SM.DNZZE,GTEX.11GS4.0011.R3b.SM.GJ3RI,GTEX.11GSO.0011.R3b.SM.57WB2,GTEX.11GSP.0011.R3a.SM.9QEGF,GTEX.11NUK.0011.R3b.SM.GJ3RO,GTEX.11NV4.0011.R3b.SM.GINAJ,...,GTEX.XLM4.0011.R10A.SM.4AT5P,GTEX.Y8DK.0011.R10A.SM.4SOK1,GTEX.YJ89.0011.R10a.SM.4SOK9,GTEX.ZF28.0011.R10a.SM.4WWEH,GTEX.ZUA1.0011.R10a.SM.51MT6,GTEX.ZV68.0011.R10a.SM.51MT7,GTEX.ZVT3.0011.R10b.SM.57WB6,GTEX.ZVZQ.0011.R10b.SM.51MRT,GTEX.ZXG5.0011.R10a.SM.57WDD,GTEX.ZZPT.0011.R10b.SM.GPI8B
0,DDX11L1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.356930,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.903235,0.000000,1.339780,1.004289,0.948680,0.000000,0.000000
1,WASH7P,122.349063,172.427568,130.200106,47.386638,103.159575,36.389517,56.991057,86.216952,177.210769,...,50.181401,83.575447,71.959244,110.194641,53.158136,99.143705,66.283074,79.689127,62.121309,76.635758
2,MIR6859-1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,MIR1302-2HG,1.699293,0.000000,0.000000,0.000000,0.000000,0.933065,1.356930,0.000000,0.000000,...,0.000000,2.785848,0.000000,0.903235,0.000000,2.679560,3.012867,1.897360,1.380474,0.870861
4,FAM138A,0.000000,0.000000,0.000000,2.016453,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.709704,0.000000,0.000000,1.004289,0.000000,0.000000,0.000000

In [49]:
# Remove duplicate genes by selecting row with highest mean expression

mean_expr = pd.DataFrame({
    'Index': range(len(bulk_expr)),
    'Gene': bulk_expr.iloc[:, 0],
    'Expr': bulk_expr.iloc[:, 1:].mean(axis=1)
})

keep = mean_expr.loc[mean_expr.groupby('Gene')['Expr'].idxmax(), 'Index']
bulk_expr_filtered = bulk_expr.iloc[keep.values]

In [ ]:
# Filter 0 genes

mask = bulk_expr_filtered.iloc[:, 1:].mean(axis=1) > 0
bulk_expr_filtered = bulk_expr_filtered[mask]

In [61]:
bulk_expr_filtered = bulk_expr_filtered.set_index("Gene")
common = bulk_expr_filtered.columns.intersection(ctype_abund_df.index)
bulk_expr_filtered = bulk_expr_filtered[common]
ctype_abund_df = ctype_abund_df.loc[common]

In [63]:
ctype_abund_df.shape

(501, 26)

In [64]:
# Correlate each cell type with gene expression

expr_corr_results = {}
for ct in ctype_abund_df.columns:
    expr_corr_results[ct] = bulk_expr_filtered.T.corrwith(ctype_abund_df[ct])
    
expr_corr_df = pd.DataFrame(expr_corr_results)

In [65]:
expr_corr_df.head()

,kelley_microglia,kelley_astro,JAKEL_2019_OLIGODENDROCYTE3,LUO_2019_ASTRO_FGF3R_CABLES1_DE_GLIAL_CLUSTERS,TRAN_DLPFC_2020_OPC,TRAN_DLPFC_2020_EXCIT_A,TRAN_AMY_2020_INHIB_B_DE_PAIRWISE,TRAN_DLPFC_2020_EXCIT_B,Micro/PVM,Oligo,...,BARRES_ASTROCYTES,ZENG_HUMAN_INTERNEURON_MARKERS,LaMANNO_PERICYTE_MIDBRAIN,YANG_PFC_2021_L4_EXCITATORY_NEURON,All GABAergic,VLMC,All Neuronal,L2/3 IT,Peri,L6 IT
Gene,,,,,,,,,,,,,,,,,,,,,
5S_rRNA,0.143395,0.019099,-0.083847,0.018168,-0.019828,0.151468,0.088607,0.128741,0.143568,-0.083847,...,0.019281,0.113517,-0.046787,0.156236,0.113705,-0.057854,0.156236,0.154598,-0.041302,0.037459
5_8S_rRNA,0.071952,0.001660,-0.016265,0.019963,0.043398,0.061319,0.122449,0.047218,0.074401,-0.016265,...,0.028613,0.128165,-0.037700,0.063453,0.127862,-0.037389,0.063453,0.077323,-0.037311,0.023519
7SK,-0.033730,0.012173,0.031057,0.033162,0.010327,0.021552,0.042980,0.034135,-0.034212,0.031057,...,0.039433,0.064756,0.007356,0.049035,0.064494,0.033431,0.049035,0.038047,-0.004496,0.055557
A1BG,0.174432,0.224893,0.189259,0.277700,0.485087,0.302052,0.455097,0.345381,0.172073,0.189259,...,0.400683,0.536340,0.083546,0.432283,0.535027,0.097177,0.432283,0.494010,0.100613,0.205803
A1BG-AS1,-0.058321,-0.342934,0.122940,-0.322080,-0.153541,0.822096,0.495128,0.870950,-0.059354,0.122940,...,-0.219270,0.573266,-0.225150,0.894040,0.573141,-0.188535,0.894040,0.727392,-0.234715,0.466322

In [66]:
expr_corr_df.to_csv(f"data/corrs/GTEx_cortex_counts_TMMF_All_501_outliers_removed_top_Qval_mods_PC1_ctype_abundance_gene_expr_corr.csv")