In [1]:
import pandas as pd

In [2]:
# For each set of cell type exons, append exon # / transcript info.

In [5]:
intron_file = "data/intron_file_transcript.tab.gz"
intron_table = pd.read_csv(intron_file, sep='\t', index_col=0)
intron_table.columns = ["intron", "event", "gene", "transcript", "exon_number"]

In [10]:
intron_table.shape

(56, 5)

In [7]:
signif_exons = pd.read_csv("data/ctype_exons/All_GABAergic_exons.csv", index_col=0)

In [8]:
signif_exons.head()

,Gene,CGE Class,All GABAergic,All Neuronal,Upper layer glutamatergic,Deep layer glutamatergic,Oligo,OPC,Astro,Micro/PVM,...,r_diff_Astro,fdr_diff_Astro,r_diff_Micro/PVM,fdr_diff_Micro/PVM,r_diff_VLMC,fdr_diff_VLMC,r_diff_Endo,fdr_diff_Endo,r_diff_Peri,fdr_diff_Peri
ENSG00000088387_ProteinCoding_1,DOCK9,0.633376,0.705695,0.623523,0.591321,0.149343,-0.523481,-0.320077,-0.474680,-0.018637,...,1.180375,0.0,0.724331,0.0,1.191689,0.0,1.339765,0.0,1.235202,0.0
ENSG00000182287_ProteinCoding_1,AP1S2,0.664130,0.704039,0.600954,0.550651,0.139004,-0.445116,-0.316596,-0.445799,-0.026693,...,1.149838,0.0,0.730731,0.0,1.171712,0.0,1.257496,0.0,1.203271,0.0
ENSG00000088387_ProteinCoding_3,DOCK9,0.665577,0.703594,0.589195,0.588405,0.066401,-0.551644,-0.236551,-0.381860,0.062814,...,1.085454,0.0,0.640780,0.0,1.061664,0.0,1.174829,0.0,1.104617,0.0
ENSG00000108262_ProteinCoding_1,GIT1,0.578142,0.700729,0.645078,0.584566,0.270527,-0.364443,-0.334427,-0.551193,-0.006634,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000165802_ProteinCoding_3,NSMF,0.538973,0.683355,0.561637,0.489399,0.294279,-0.282205,-0.257838,-0.529562,0.004572,...,1.212917,0.0,0.678783,0.0,1.074655,0.0,1.219446,0.0,1.077396,0.0

In [9]:
signif_exons.merge(intron_table, left_index=True, right_index=True, how='left')

,Gene,CGE Class,All GABAergic,All Neuronal,Upper layer glutamatergic,Deep layer glutamatergic,Oligo,OPC,Astro,Micro/PVM,...,fdr_diff_VLMC,r_diff_Endo,fdr_diff_Endo,r_diff_Peri,fdr_diff_Peri,intron,event,gene,transcript,exon_number
ENSG00000088387_ProteinCoding_1,DOCK9,0.633376,0.705695,0.623523,0.591321,0.149343,-0.523481,-0.320077,-0.474680,-0.018637,...,0.0,1.339765,0.0,1.235202,0.0,NaN,NaN,NaN,NaN,NaN
ENSG00000182287_ProteinCoding_1,AP1S2,0.664130,0.704039,0.600954,0.550651,0.139004,-0.445116,-0.316596,-0.445799,-0.026693,...,0.0,1.257496,0.0,1.203271,0.0,NaN,NaN,NaN,NaN,NaN
ENSG00000088387_ProteinCoding_3,DOCK9,0.665577,0.703594,0.589195,0.588405,0.066401,-0.551644,-0.236551,-0.381860,0.062814,...,0.0,1.174829,0.0,1.104617,0.0,NaN,NaN,NaN,NaN,NaN
ENSG00000108262_ProteinCoding_1,GIT1,0.578142,0.700729,0.645078,0.584566,0.270527,-0.364443,-0.334427,-0.551193,-0.006634,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000165802_ProteinCoding_3,NSMF,0.538973,0.683355,0.561637,0.489399,0.294279,-0.282205,-0.257838,-0.529562,0.004572,...,0.0,1.219446,0.0,1.077396,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000054796_NMD_1,SPO11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000237484_other_11,LINC01684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000159261_ProteinCoding_1,CLDN14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000160191_ProteinCoding_13,PDE9A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000278057_other_1,TEX28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN