In [3]:
# conda activate psix

import os
import sys
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

sys.path.append("code")

from modified_functions import *

In [4]:
# Load GTF

exclude = ""
gene_name = "gene_id"
gene_type = "all"
no_trim_id = False
gene_type_tag = "gene_type"
transcript_type_tag = "transcript_type"

gtf_file = "/mnt/lareaulab/reliscu/data/GENCODE/GRCh38/gencode.v46.annotation.gtf"
gtf = process_gtf(gtf_file, exclude, gene_name, no_trim_id, gene_type_tag, transcript_type_tag)
# gtf.exon_number = gtf.exon_number.astype(int)

Processing GTF file...

INFO:root:Extracted GTF attributes: ['gene_id', 'gene_type', 'gene_name', 'level', 'tag', 'transcript_id', 'transcript_type', 'transcript_name', 'transcript_support_level', 'havana_transcript', 'exon_number', 'exon_id', 'hgnc_id', 'havana_gene', 'ont', 'protein_id', 'ccdsid', 'artif_dupl']

## Get info. for all exons

In [ ]:


# Load intron table (with junctions per event)

intron_file = "/mnt/lareaulab/reliscu/data/GENCODE/GRCh38/psix_annotation/intron_file.tab.gz"
intron_table = pd.read_csv(intron_file, sep='\t', index_col=0)

intron_table_parsed = intron_table.copy()
coords = intron_table_parsed['intron'].str.split(':').str[1].str.split('-')
intron_table_parsed['intron_start'] = coords.str[0].astype(int)
intron_table_parsed['intron_end'] = coords.str[1].astype(int)

In [ ]:
# Do this ONCE before the loop

gtf_exon = gtf[gtf.feature == "exon"]
gtf_indexed = gtf_exon.set_index(['chrom', 'start', 'end']).sort_index() # for exon lookup
exons_by_transcript = {t: grp for t, grp in gtf_exon.groupby('transcript')}  # for transcript lookup

In [72]:
gtf_cds = gtf[gtf.feature == "CDS"]
cds_by_transcript = {t: grp for t, grp in gtf_cds.groupby('transcript')}  # for transcript lookup

In [136]:
gtf_sc = gtf[gtf.feature == "start_codon"]
sc_by_transcript = {t: grp for t, grp in gtf_sc.groupby('transcript')}  # for transcript lookup

In [10]:
# Compile list of all exons from cell type splicing analysis
exon_lookup = {}
for file in os.listdir("data/ctype_exons"):
    if file.endswith("exons.csv"):
        signif_exons_df = pd.read_csv(f"data/ctype_exons/{file}", index_col=0)
        signif_exons_df = signif_exons_df[~np.isnan(signif_exons_df['Oligo'])]  # keep as DataFrame, not just index
        
        for idx, row in signif_exons_df.iterrows():
            if idx not in exon_lookup:  # skip if already seen
                exon_lookup[idx] = {
                    "chr": row['chr'],
                    "exon_start": row['exon_start'],
                    "exon_end": row['exon_end']
                }

In [ ]:
exon_info = {}

# For each splicing event: save transcripts with compatible_transcripts splice junctions

for idx, val in tqdm(exon_lookup.items(), total=len(exon_lookup)):
    start, end, chrom = val['exon_start'], val['exon_end'], val['chr']
    target_exon = gtf_indexed.loc[(chrom, start, end)]
    strand = target_exon.strand.values[0]
 
    event_introns = intron_table_parsed[intron_table_parsed.event == idx]
    i1 = event_introns[event_introns.index.str.endswith("I1")]
    i2 = event_introns[event_introns.index.str.endswith("I2")]
    upstream_intron_start = i1.intron_start.values[0]
    downstream_intron_end = i2.intron_end.values[0]

    compatible_transcripts_transcripts = {}
     
    for _, exon_row in target_exon.iterrows():
        target_transcript = exon_row['transcript']
        exon_number = int(exon_row['exon_number'])
        transcript_exons = exons_by_transcript.get(target_transcript)

        # Get flanking exon boundaries (direction depends on sense)
        upstream_num, downstream_num = (exon_number + 1, exon_number - 1) if strand == "-" else (exon_number - 1, exon_number + 1) 
        te_indexed = transcript_exons.set_index(transcript_exons['exon_number'].astype(int))
        
        if upstream_num not in te_indexed.index or downstream_num not in te_indexed.index:
            continue  # exon is the last/first in this transcript

        upstream_exon_end = te_indexed.loc[upstream_num, 'end']
        downstream_exon_start = te_indexed.loc[downstream_num, 'start']

        if (upstream_intron_start == (upstream_exon_end + 1)) and (downstream_intron_end == (downstream_exon_start - 1)):
            compatible_transcripts_transcripts[target_transcript] = {
                "transcript_type": transcript_exons.transcript_type.values[0], 
                "exon_number": exon_number
            }
            
    exon_info[idx] = compatible_transcripts_transcripts

 12%|█▏        | 3438/28837 [00:39<04:51, 87.18it/s]

KeyboardInterrupt:

In [ ]:

def is_exon_coding(exon_start, exon_end, transcript_cds_rows):
    for _, cds in transcript_cds_rows.iterrows():
        if exon_start >= cds['start'] and exon_end <= cds['end']:
            return True
    return False

In [106]:
cds_by_transcript

{'ENST00000000233':         chrom      start        end feature strand       transcript  \
 1405255  chr7  127588499  127588565     CDS      +  ENST00000000233
 1405258  chr7  127589083  127589163     CDS      +  ENST00000000233
 1405260  chr7  127589485  127589594     CDS      +  ENST00000000233
 1405262  chr7  127590066  127590137     CDS      +  ENST00000000233
 1405264  chr7  127590963  127591088     CDS      +  ENST00000000233
 1405266  chr7  127591213  127591296     CDS      +  ENST00000000233

               gene_type             gene transcript_type exon_number  frame  \
 1405255  protein_coding  ENSG00000004059  protein_coding           1      0
 1405258  protein_coding  ENSG00000004059  protein_coding           2      2
 1405260  protein_coding  ENSG00000004059  protein_coding           3      2
 1405262  protein_coding  ENSG00000004059  protein_coding           4      0
 1405264  protein_coding  ENSG00000004059  protein_coding           5      0
 1405266  protein_coding  ENSG00000004059  protein_coding           6      0

                                                        tag         protein_id
 1405255  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000233.5
 1405258  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000233.5
 1405260  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000233.5
 1405262  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000233.5
 1405264  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000233.5
 1405266  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000233.5  ,
 'ENST00000000412':          chrom    start      end feature strand       transcript  \
 2063659  chr12  8946229  8946404     CDS      -  ENST00000000412
 2063662  chr12  8945418  8945584     CDS      -  ENST00000000412
 2063664  chr12  8943801  8943910     CDS      -  ENST00000000412
 2063666  chr12  8943405  8943535     CDS      -  ENST00000000412
 2063668  chr12  8942416  8942542     CDS      -  ENST00000000412
 2063670  chr12  8941821  8941940     CDS      -  ENST00000000412

               gene_type             gene transcript_type exon_number  frame  \
 2063659  protein_coding  ENSG00000003056  protein_coding           2      0
 2063662  protein_coding  ENSG00000003056  protein_coding           3      1
 2063664  protein_coding  ENSG00000003056  protein_coding           4      2
 2063666  protein_coding  ENSG00000003056  protein_coding           5      0
 2063668  protein_coding  ENSG00000003056  protein_coding           6      1
 2063670  protein_coding  ENSG00000003056  protein_coding           7      0

                                                        tag         protein_id
 2063659  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000412.3
 2063662  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000412.3
 2063664  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000412.3
 2063666  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000412.3
 2063668  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000412.3
 2063670  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000000412.3  ,
 'ENST00000000442':          chrom     start       end feature strand       transcript  \
 1932398  chr11  64307180  64307504     CDS      +  ENST00000000442
 1932401  chr11  64313951  64314067     CDS      +  ENST00000000442
 1932403  chr11  64314239  64314367     CDS      +  ENST00000000442
 1932405  chr11  64314741  64314911     CDS      +  ENST00000000442
 1932407  chr11  64315001  64315270     CDS      +  ENST00000000442
 1932409  chr11  64315707  64315963     CDS      +  ENST00000000442

               gene_type             gene transcript_type exon_number  frame  \
 1932398  protein_coding  ENSG00000173153  protein_coding           2      0
 1932401  protein_coding  ENSG00000173153  protein_coding           3      2
 1932403  protein_coding  ENSG00000173153  protein_coding           4      2
 1932405  protein_coding  ENSG00000173153  protein_coding           5      2
 1932407  protein_coding  ENSG00000173153  protein_coding           6      2
 1932409  protein_coding  ENSG00000173153  protein_coding           7      2

                                                        tag         protein_id
 1932398  NAGNAG_splice_site,basic,Ensembl_canonical,GEN...  ENSP00000000442.6
 1932401  NAGNAG_splice_site,basic,Ensembl_canonical,GEN...  ENSP00000000442.6
 1932403  NAGNAG_splice_site,basic,Ensembl_canonical,GEN...  ENSP00000000442.6
 1932405  NAGNAG_splice_site,basic,Ensembl_canonical,GEN...  ENSP00000000442.6
 1932407  NAGNAG_splice_site,basic,Ensembl_canonical,GEN...  ENSP00000000442.6
 1932409  NAGNAG_splice_site,basic,Ensembl_canonical,GEN...  ENSP00000000442.6  ,
 'ENST00000001008':          chrom    start      end feature strand       transcript  \
 2047152  chr12  2795140  2795244     CDS      +  ENST00000001008
 2047155  chr12  2797138  2797282     CDS      +  ENST00000001008
 2047157  chr12  2797729  2797871     CDS      +  ENST00000001008
 2047159  chr12  2798706  2798826     CDS      +  ENST00000001008
 2047161  chr12  2799088  2799244     CDS      +  ENST00000001008
 2047163  chr12  2799850  2799940     CDS      +  ENST00000001008
 2047165  chr12  2800039  2800122     CDS      +  ENST00000001008
 2047167  chr12  2800392  2800577     CDS      +  ENST00000001008
 2047169  chr12  2801117  2801356     CDS      +  ENST00000001008
 2047171  chr12  2803151  2803255     CDS      +  ENST00000001008

               gene_type             gene transcript_type exon_number  frame  \
 2047152  protein_coding  ENSG00000004478  protein_coding           1      0
 2047155  protein_coding  ENSG00000004478  protein_coding           2      0
 2047157  protein_coding  ENSG00000004478  protein_coding           3      2
 2047159  protein_coding  ENSG00000004478  protein_coding           4      0
 2047161  protein_coding  ENSG00000004478  protein_coding           5      2
 2047163  protein_coding  ENSG00000004478  protein_coding           6      1
 2047165  protein_coding  ENSG00000004478  protein_coding           7      0
 2047167  protein_coding  ENSG00000004478  protein_coding           8      0
 2047169  protein_coding  ENSG00000004478  protein_coding           9      0
 2047171  protein_coding  ENSG00000004478  protein_coding          10      0

                                                        tag         protein_id
 2047152  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047155  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047157  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047159  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047161  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047163  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047165  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047167  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047169  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4
 2047171  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001008.4  ,
 'ENST00000001146':        chrom     start       end feature strand       transcript  \
 403906  chr2  72147631  72147834     CDS      -  ENST00000001146
 403909  chr2  72143989  72144213     CDS      -  ENST00000001146
 403911  chr2  72135144  72135419     CDS      -  ENST00000001146
 403913  chr2  72134761  72134916     CDS      -  ENST00000001146
 403915  chr2  72133023  72133307     CDS      -  ENST00000001146
 403917  chr2  72132230  72132619     CDS      -  ENST00000001146

              gene_type             gene transcript_type exon_number  frame  \
 403906  protein_coding  ENSG00000003137  protein_coding           1      0
 403909  protein_coding  ENSG00000003137  protein_coding           2      0
 403911  protein_coding  ENSG00000003137  protein_coding           3      0
 403913  protein_coding  ENSG00000003137  protein_coding           4      0
 403915  protein_coding  ENSG00000003137  protein_coding           5      0
 403917  protein_coding  ENSG00000003137  protein_coding           6      0

                                                       tag         protein_id
 403906  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001146.2
 403909  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001146.2
 403911  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001146.2
 403913  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001146.2
 403915  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001146.2
 403917  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000001146.2  ,
 'ENST00000002125':        chrom     start       end feature strand       transcript  \
 362426  chr2  37231706  37231760     CDS      +  ENST00000002125
 362429  chr2  37232106  37232266     CDS      +  ENST00000002125
 362431  chr2  37236096  37236176     CDS      +  ENST00000002125
 362433  chr2  37237757  37237867     CDS      +  ENST00000002125
 362435  chr2  37241578  37241791     CDS      +  ENST00000002125
 362437  chr2  37242635  37242693     CDS      +  ENST00000002125
 362439  chr2  37243863  37243973     CDS      +  ENST00000002125
 362441  chr2  37246052  37246195     CDS      +  ENST00000002125
 362443  chr2  37247456  37247629     CDS      +  ENST00000002125
 362445  chr2  37248135  37248347     CDS      +  ENST00000002125

              gene_type             gene transcript_type exon_number  frame  \
 362426  protein_coding  ENSG00000003509  protein_coding           1      0
 362429  protein_coding  ENSG00000003509  protein_coding           2      2
 362431  protein_coding  ENSG00000003509  protein_coding           3      0
 362433  protein_coding  ENSG00000003509  protein_coding           4      0
 362435  protein_coding  ENSG00000003509  protein_coding           5      0
 362437  protein_coding  ENSG00000003509  protein_coding           6      2
 362439  protein_coding  ENSG00000003509  protein_coding           7      0
 362441  protein_coding  ENSG00000003509  protein_coding           8      0
 362443  protein_coding  ENSG00000003509  protein_coding           9      0
 362445  protein_coding  ENSG00000003509  protein_coding          10      0

                                                       tag         protein_id
 362426  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362429  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362431  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362433  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362435  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362437  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362439  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362441  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362443  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4
 362445  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002125.4  ,
 'ENST00000002165':         chrom      start        end feature strand       transcript  \
 1251994  chr6  143511411  143511634     CDS      -  ENST00000002165
 1251997  chr6  143507237  143507424     CDS      -  ENST00000002165
 1251999  chr6  143503913  143504252     CDS      -  ENST00000002165
 1252001  chr6  143502355  143502565     CDS      -  ENST00000002165
 1252003  chr6  143501932  143502122     CDS      -  ENST00000002165
 1252005  chr6  143497389  143497497     CDS      -  ENST00000002165
 1252007  chr6  143495710  143495847     CDS      -  ENST00000002165

               gene_type             gene transcript_type exon_number  frame  \
 1251994  protein_coding  ENSG00000001036  protein_coding           1      0
 1251997  protein_coding  ENSG00000001036  protein_coding           2      1
 1251999  protein_coding  ENSG00000001036  protein_coding           3      2
 1252001  protein_coding  ENSG00000001036  protein_coding           4      1
 1252003  protein_coding  ENSG00000001036  protein_coding           5      0
 1252005  protein_coding  ENSG00000001036  protein_coding           6      1
 1252007  protein_coding  ENSG00000001036  protein_coding           7      0

                                                        tag         protein_id
 1251994  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002165.5
 1251997  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002165.5
 1251999  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002165.5
 1252001  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002165.5
 1252003  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002165.5
 1252005  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002165.5
 1252007  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002165.5  ,
 'ENST00000002501':          chrom     start       end feature strand       transcript  \
 2687659  chr16  90019311  90019341     CDS      -  ENST00000002501
 2687662  chr16  90009284  90009430     CDS      -  ENST00000002501
 2687664  chr16  90008784  90008924     CDS      -  ENST00000002501
 2687666  chr16  90006338  90006492     CDS      -  ENST00000002501

               gene_type             gene transcript_type exon_number  frame  \
 2687659  protein_coding  ENSG00000003249  protein_coding           1      0
 2687662  protein_coding  ENSG00000003249  protein_coding           2      2
 2687664  protein_coding  ENSG00000003249  protein_coding           3      2
 2687666  protein_coding  ENSG00000003249  protein_coding           4      2

                                                        tag         protein_id
 2687659  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002501.6
 2687662  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002501.6
 2687664  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002501.6
 2687666  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002501.6  ,
 'ENST00000002596':        chrom     start       end feature strand       transcript  \
 832373  chr4  11399085  11400005     CDS      -  ENST00000002596

              gene_type             gene transcript_type exon_number  frame  \
 832373  protein_coding  ENSG00000002587  protein_coding           2      0

                                                       tag         protein_id
 832373  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002596.5  ,
 'ENST00000002829':        chrom     start       end feature strand       transcript  \
 666876  chr3  50159623  50159734     CDS      +  ENST00000002829
 666879  chr3  50173793  50173953     CDS      +  ENST00000002829
 666881  chr3  50174052  50174114     CDS      +  ENST00000002829
 666883  chr3  50174231  50174350     CDS      +  ENST00000002829
 666885  chr3  50175096  50175188     CDS      +  ENST00000002829
 666887  chr3  50176768  50176861     CDS      +  ENST00000002829
 666889  chr3  50182284  50182403     CDS      +  ENST00000002829
 666891  chr3  50182644  50182783     CDS      +  ENST00000002829
 666893  chr3  50182904  50183018     CDS      +  ENST00000002829
 666895  chr3  50183186  50183255     CDS      +  ENST00000002829
 666897  chr3  50183420  50183564     CDS      +  ENST00000002829
 666899  chr3  50184592  50184814     CDS      +  ENST00000002829
 666901  chr3  50185443  50185531     CDS      +  ENST00000002829
 666903  chr3  50185666  50185707     CDS      +  ENST00000002829
 666905  chr3  50185889  50186046     CDS      +  ENST00000002829
 666907  chr3  50186281  50186348     CDS      +  ENST00000002829
 666909  chr3  50186613  50186746     CDS      +  ENST00000002829
 666911  chr3  50187705  50188112     CDS      +  ENST00000002829

              gene_type             gene transcript_type exon_number  frame  \
 666876  protein_coding  ENSG00000001617  protein_coding           2      0
 666879  protein_coding  ENSG00000001617  protein_coding           3      2
 666881  protein_coding  ENSG00000001617  protein_coding           4      0
 666883  protein_coding  ENSG00000001617  protein_coding           5      0
 666885  protein_coding  ENSG00000001617  protein_coding           6      0
 666887  protein_coding  ENSG00000001617  protein_coding           7      0
 666889  protein_coding  ENSG00000001617  protein_coding           8      2
 666891  protein_coding  ENSG00000001617  protein_coding           9      2
 666893  protein_coding  ENSG00000001617  protein_coding          10      0
 666895  protein_coding  ENSG00000001617  protein_coding          11      2
 666897  protein_coding  ENSG00000001617  protein_coding          12      1
 666899  protein_coding  ENSG00000001617  protein_coding          13      0
 666901  protein_coding  ENSG00000001617  protein_coding          14      2
 666903  protein_coding  ENSG00000001617  protein_coding          15      0
 666905  protein_coding  ENSG00000001617  protein_coding          16      0
 666907  protein_coding  ENSG00000001617  protein_coding          17      1
 666909  protein_coding  ENSG00000001617  protein_coding          18      2
 666911  protein_coding  ENSG00000001617  protein_coding          19      0

                                                       tag         protein_id
 666876  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666879  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666881  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666883  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666885  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666887  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666889  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666891  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666893  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666895  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666897  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666899  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666901  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666903  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666905  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666907  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666909  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3
 666911  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...  ENSP00000002829.3  ,
 'ENST00000003084':         chrom      start        end feature strand       transcript  \
 1398755  chr7  117480095  117480147     CDS      +  ENST00000003084
 1398758  chr7  117504253  117504363     CDS      +  ENST00000003084
 1398760  chr7  117509034  117509142     CDS      +  ENST00000003084
 1398762  chr7  117530899  117531114     CDS      +  ENST00000003084
 1398764  chr7  117534276  117534365     CDS      +  ENST00000003084
 1398766  chr7  117535248  117535411     CDS      +  ENST00000003084
 1398768  chr7  117536548  117536673     CDS      +  ENST00000003084
 1398770  chr7  117540100  117540346     CDS      +  ENST00000003084
 1398772  chr7  117542016  117542108     CDS      +  ENST00000003084
 1398774  chr7  117548641  117548823     CDS      +  ENST00000003084
 1398776  chr7  117559464  117559655     CDS      +  ENST00000003084
 1398778  chr7  117587739  117587833     CDS      +  ENST00000003084
 1398780  chr7  117590353  117590439     CDS      +  ENST00000003084
 1398782  chr7  117591934  117592657     CDS      +  ENST00000003084

In [134]:
from Bio import SeqIO
genome = SeqIO.to_dict(SeqIO.parse("genome.fa", "fasta"))

ModuleNotFoundError: No module named 'Bio'

In [ ]:
target_exon

                          feature strand       transcript       gene_type  \
chrom start     end
chr9  137023838 137023840    exon      -  ENST00000341511  protein_coding
                137023840    exon      -  ENST00000614293  protein_coding
                137023840    exon      -  ENST00000494046  protein_coding
                137023840    exon      -  ENST00000476211  protein_coding

                                      gene  transcript_type exon_number  \
chrom start     end
chr9  137023838 137023840  ENSG00000107331   protein_coding           3
                137023840  ENSG00000107331   protein_coding           3
                137023840  ENSG00000107331  retained_intron           3
                137023840  ENSG00000107331  retained_intron           3

                           frame  \
chrom start     end
chr9  137023838 137023840      0
                137023840      0
                137023840      0
                137023840      0

                                                                         tag  \
chrom start     end
chr9  137023838 137023840  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...
                137023840  inferred_transcript_model,basic,GENCODE_Primar...
                137023840                                        mRNA_end_NF
                137023840

                                  protein_id
chrom start     end
chr9  137023838 137023840  ENSP00000344155.6
                137023840  ENSP00000481105.2
                137023840
                137023840

In [ ]:
type()

numpy.int64

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [207]:
target_exon

                          feature strand       transcript       gene_type  \
chrom start     end
chr9  137023838 137023840    exon      -  ENST00000341511  protein_coding
                137023840    exon      -  ENST00000614293  protein_coding
                137023840    exon      -  ENST00000494046  protein_coding
                137023840    exon      -  ENST00000476211  protein_coding

                                      gene  transcript_type exon_number  \
chrom start     end
chr9  137023838 137023840  ENSG00000107331   protein_coding           3
                137023840  ENSG00000107331   protein_coding           3
                137023840  ENSG00000107331  retained_intron           3
                137023840  ENSG00000107331  retained_intron           3

                           frame  \
chrom start     end
chr9  137023838 137023840      0
                137023840      0
                137023840      0
                137023840      0

                                                                         tag  \
chrom start     end
chr9  137023838 137023840  basic,Ensembl_canonical,GENCODE_Primary,MANE_S...
                137023840  inferred_transcript_model,basic,GENCODE_Primar...
                137023840                                        mRNA_end_NF
                137023840

                                  protein_id
chrom start     end
chr9  137023838 137023840  ENSP00000344155.6
                137023840  ENSP00000481105.2
                137023840
                137023840

In [ ]:
exon_info = {}
exon_coding_info = {}

# For each splicing event: save transcripts with compatible_transcripts splice junctions

for idx, val in tqdm(exon_lookup.items(), total=len(exon_lookup)):
    start, end, chrom = val['exon_start'], val['exon_end'], val['chr']
    target_exon = gtf_indexed.loc[(chrom, start, end)]
    strand = target_exon.strand.values[0]
    
    event_introns = intron_table_parsed[intron_table_parsed.event == idx]
    i1 = event_introns[event_introns.index.str.endswith("I1")]
    i2 = event_introns[event_introns.index.str.endswith("I2")]
    upstream_intron_start = i1.intron_start.values[0]
    downstream_intron_end = i2.intron_end.values[0]

    compatible_transcripts = {}

    for _, exon_row in target_exon.iterrows():
        target_transcript = exon_row['transcript']
        exon_number = int(exon_row['exon_number'])
        all_exons_in_transcript = exons_by_transcript.get(target_transcript)

        # Get flanking exon boundaries (direction depends on sense)
        upstream_num, downstream_num = (
            (exon_number + 1, exon_number - 1) if strand == "-" else (exon_number - 1, exon_number + 1)
        ) 
        te_indexed = all_exons_in_transcript.set_index(all_exons_in_transcript['exon_number'].astype(int))
        
        if upstream_num not in te_indexed.index or downstream_num not in te_indexed.index:
            continue  # if exon is the last/first exon in this particular transcript

        upstream_exon_end = te_indexed.loc[upstream_num, 'end']
        downstream_exon_start = te_indexed.loc[downstream_num, 'start']

        if (upstream_intron_start == (upstream_exon_end + 1)) and (downstream_intron_end == (downstream_exon_start - 1)):
            compatible_transcripts[target_transcript] = {
                "strand": strand,
                "transcript_type": all_exons_in_transcript.transcript_type.values[0], 
                "exon_number": exon_number,
                "tag": all_exons_in_transcript.tag.values[0]
            }
            
            # If transcript codes for a protein, get additional info:
            transcript_cds = cds_by_transcript.get(target_transcript)
            if transcript_cds is not None and is_exon_coding(start, end, transcript_cds):
                
                spliced_offset = 0      # get position of exon in spliced mRNA 
                                        # (sum up lengths of coding exons preceding target exon)
                for _, cds in transcript_cds.iterrows():
                    if cds['start'] == start and cds['end'] == end:
                        break   # reached our exon, stop
                    spliced_offset += cds['end'] - cds['start'] + 1
                
                exon_cds_start = spliced_offset
                exon_cds_end = spliced_offset + (end - start)

                this_cds_frame = (3 - (exon_cds_start % 3)) % 3
                expected_frame = transcript_cds[transcript_cds.exon_number.values.astype(int) == exon_number].frame.values[0]
                assert(expected_frame == this_cds_frame), f"Frame mismatch: {idx}"
                          
                compatible_transcripts[target_transcript]["aa_start"] = exon_cds_start // 3
                compatible_transcripts[target_transcript]["aa_end"] = exon_cds_end // 3

    exon_info[idx] = compatible_transcripts
    # if len(compatible_transcripts) > 1:
    #     break

  0%|          | 0/28837 [00:00<?, ?it/s]

## Now append exon info. to cell type exon analysis results

In [17]:
rows = []
for idx, transcripts in exon_info.items():
    rows.append({
        'exon': idx,
        'transcripts': ','.join(transcripts.keys()),
        'transcript_types': ','.join(info['transcript_type'] for info in transcripts.values()),
        'exon_numbers': ','.join(str(info['exon_number']) for info in transcripts.values())
    })

exon_info_df = pd.DataFrame(rows).set_index('exon')

In [20]:
exon_info_df.head()

,transcripts,transcript_types,exon_numbers
exon,,,
ENSG00000107331_ProteinCoding_2,"ENST00000341511,ENST00000614293,ENST0000049404...","protein_coding,protein_coding,retained_intron,...","3,3,3,3"
ENSG00000277363_other_1,ENST00000621763,protein_coding_CDS_not_defined,17
ENSG00000203485_ProteinCoding_12,"ENST00000392634,ENST00000675207,ENST0000061757...","protein_coding,protein_coding,nonsense_mediate...","22,22,21,21"
ENSG00000151150_ProteinCoding_3,"ENST00000503366,ENST00000373827,ENST0000037382...","protein_coding,protein_coding,protein_coding,p...","40,40,7,17"
ENSG00000135905_ProteinCoding_2,ENST00000535663,protein_coding,2

In [52]:
column_order = ['Gene', 'is_specific', 'specific_direction', 'exon_len', 
                'chr', 'exon_start', 'exon_end', 'transcripts', 'transcript_types', 'exon_numbers',
                'r', 'fdr', 
                'CGE Class', 'All GABAergic', 'All Neuronal',
                'Upper layer glutamatergic', 'Deep layer glutamatergic', 'Oligo', 'OPC',
                'Astro', 'Micro/PVM', 'VLMC', 'Endo', 'Peri'
                ]

In [62]:
for file in os.listdir("data/ctype_exons"):
    if file.endswith("exons.csv"):
        print(file)
        signif_exons_df = pd.read_csv(f"data/ctype_exons/{file}", index_col=0)
        signif_exons_df = signif_exons_df[~np.isnan(signif_exons_df['Oligo'])] 
        signif_exons_info = exon_info_df.merge(
            signif_exons_df, left_index=True, right_index=True,
            how='right'
        )
        rest_columns = signif_exons_info.columns[signif_exons_info.columns.str.contains("diff")].tolist() 
        new_file = file.replace('_exons.csv', '_exons_annotated.csv')
        signif_exons_info[column_order + rest_columns].to_csv(f"data/ctype_exons/annotated/{new_file}")

Oligo_exons.csv
VLMC_exons.csv
Endo_exons.csv
Deep_layer_glutamatergic_exons.csv
Astro_exons.csv
OPC_exons.csv
Micro_PVM_exons.csv
All_Neuronal_exons.csv
All_GABAergic_exons.csv
Peri_exons.csv
CGE_Class_exons.csv
Upper_layer_glutamatergic_exons.csv